-- ─────────────────────────────────────────────────────────────────────────────
-- OBSOLETE — DO NOT RUN.
--
-- This used Supabase pg_cron + pg_net to poke /api/cron/reminders every minute
-- back when Vercel Hobby crons ran at most once a day. Cloudflare now fires
-- "* * * * *" → /api/cron/reminders itself (cf-worker.ts CRON_ROUTES), and the
-- route accepts the secret ONLY as an Authorization header, so the old
-- `?secret=` URL below was answered 403 on every ping.
--
-- The live job ('borivon-fire-reminders') was found by the D1-migration catalog
-- check and removed on 2026-09-11 with:
--   select cron.unschedule(jobid) from cron.job where command like '%/api/cron/reminders%';
-- Nothing else is scheduled inside Supabase.
-- ─────────────────────────────────────────────────────────────────────────────
