// @ts-nocheck — build-glue, bundled by wrangler/esbuild (not part of the app's tsc surface).
// The path "./.open-next/worker.js" is GENERATED by `opennextjs-cloudflare build` at build time.
//
// Custom Cloudflare Worker entry. OpenNext only emits a `fetch` handler, but the bot's
// proactive automation (daily briefing, midday/evening nudges, weekly report, auto-chase,
// inbox reminder + the SLA/follow-up chase that ride them) runs on CRON. On Vercel those are
// vercel.json "crons"; on Cloudflare we need a `scheduled()` handler + wrangler triggers.crons.
// This wraps the generated handler (re-using its fetch + re-exporting its Durable Objects) and
// adds scheduled(), dispatching each cron to its existing /api/cron/* route IN-WORKER (no
// external HTTP), authenticated with CRON_SECRET exactly like Vercel's cron calls.
// Supported pattern: https://opennext.js.org/cloudflare/howtos/custom-worker
import { default as handler } from "./.open-next/worker.js";

// Re-export the Durable Objects the generated worker defines, or their bindings break.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";

// Each wrangler cron expression → the route it invokes. MUST stay byte-identical to the
// cron strings in wrangler.jsonc triggers.crons (Cloudflare passes the matched string), and
// mirror vercel.json "crons" so both platforms run the same scheduled work.
const CRON_ROUTES = {
  "0 6 * * *": "/api/cron/briefing",
  "0 12 * * *": "/api/cron/nudge?slot=midday",
  "0 17 * * *": "/api/cron/nudge?slot=evening",
  "0 7 * * 1": "/api/cron/weekly-report",
  "0 8 * * *": "/api/cron/auto-chase",
  "30 8 * * *": "/api/cron/inbox-reminder",
};

export default {
  fetch: handler.fetch,
  async scheduled(event, env, ctx) {
    // DORMANT until cutover: while Vercel is still live it ALSO runs these crons, so firing
    // here too would double every briefing/nudge to the founder. The triggers are registered
    // + the handler is ready; it only DISPATCHES once env.CF_CRONS_ENABLED === "true" (set that
    // Worker secret at cutover, the same moment Vercel's crons are removed). Until then: no-op.
    if (env.CF_CRONS_ENABLED !== "true") {
      console.log(`[cron] dormant (CF_CRONS_ENABLED!=true) — skipped ${event.cron}`);
      return;
    }
    const path = CRON_ROUTES[event.cron];
    if (!path) {
      console.error("[cron] no route mapped for", event.cron);
      return;
    }
    const secret = env.CRON_SECRET;
    // Dispatch through the SAME Next handler in-worker. The host is irrelevant — OpenNext
    // routes by pathname; the /api/cron/* route enforces the Bearer CRON_SECRET itself.
    const req = new Request(`https://cron.internal${path}`, {
      headers: secret ? { authorization: `Bearer ${secret}` } : {},
    });
    ctx.waitUntil(
      handler
        .fetch(req, env, ctx)
        .then((res) => {
          if (!res || !res.ok) console.error(`[cron] ${event.cron} → ${path} failed: ${res ? res.status : "no response"}`);
          else console.log(`[cron] ${event.cron} → ${path} ok`);
        })
        .catch((e) => console.error(`[cron] ${event.cron} → ${path} threw:`, e instanceof Error ? e.message : e)),
    );
  },
};
