/**
 * Value codec for the PostgREST→D1 adapter: SQLite values ⇄ what the 1,261
 * existing `.from(...)` call sites already receive from Supabase.
 *
 *   D1 row  → decodeRows()  → response body   (what supabase-js hands the caller)
 *   JS value → encodeValue() → bound parameter (what buildSql() sends to D1)
 *
 * The two halves must be exact inverses, because the D1 copy was written by
 * d1/export-data.mjs `encodeParam()` reading live PostgREST output. Whatever
 * that function did on the way IN, decodeValue() has to undo on the way OUT, or
 * a candidate's `documents.uploaded_by_admin` comes back as the number 1 and
 * `if (doc.uploaded_by_admin === true)` silently stops matching. Hence:
 *
 *   Postgres type   D1 storage (d1/schema.sql)   what callers expect back
 *   ─────────────   ──────────────────────────   ────────────────────────
 *   boolean         INTEGER 0 / 1                true / false
 *   integer/bigint  INTEGER                      number
 *   numeric         REAL                         number
 *   jsonb           TEXT holding JSON            parsed object/array/scalar
 *   text[] uuid[]   TEXT holding a JSON array    parsed array
 *   uuid text date  TEXT                         the same string
 *   timestamptz     TEXT, already in Postgres's  the same string
 *                   `…T17:25:01.155+00:00` form
 *
 * Everything here is pure: no D1 client, no fetch, no globals. The registry
 * (d1/types.json, regenerated by d1/gen-schema.mjs) is the only type source —
 * SQLite's own column affinity cannot tell a boolean from an integer, nor JSON
 * text from ordinary text, so guessing from the value is never an option.
 */
import type { JsonOp, PgType, QueryIntent, Registry, SelectItem } from "./types";

/* ────────────────────────────── helpers ────────────────────────────── */

/** Postgres boolean input literals (`SELECT 'yes'::boolean` works). */
const BOOL_TRUE = new Set(["true", "t", "yes", "y", "on", "1"]);
const BOOL_FALSE = new Set(["false", "f", "no", "n", "off", "0"]);

/** A full ISO-8601 instant — date, time and a zone. Partial values like the
 *  `"2026-09-01"` people pass to `.gte("created_at", …)` deliberately do NOT
 *  match: a bare date is already a correct lexical lower bound for that day. */
const ISO_INSTANT = /^\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})$/;

/**
 * An ISO UTC instant → the TEXT PostgREST would have produced for it: a `+00:00`
 * offset instead of `Z`, and Postgres's trailing-zero trimming of the fraction.
 *
 * Postgres prints `17:25:01.15+00:00` for 150 ms and `17:25:01+00:00` for a whole
 * second — it never pads. The stored rows came from PostgREST, so a value we
 * build has to compare against them as TEXT: `.150+00:00` is the same instant as
 * the `.15+00:00` sitting in the table but a different string, so `.eq()` would
 * miss it and `.gte()` would sort it on the wrong side. `new Date().toISOString()`
 * always emits exactly three fraction digits, so ~10% of the timestamps the call
 * sites hand us (`created_at: new Date().toISOString()`, lib/assistantWrites.ts:190)
 * end in a zero and need this.
 */
function toStoredTimestamp(isoUtc: string): string {
  const body = isoUtc.endsWith("Z") ? isoUtc.slice(0, -1) : isoUtc;
  return `${body.replace(/\.(\d+)$/, (_m, frac: string) => {
    const trimmed = frac.replace(/0+$/, "");
    return trimmed ? `.${trimmed}` : "";
  })}+00:00`;
}

/** The same, for a Date — the only shape that reaches us without a `Z` string. */
function dateToStoredTimestamp(d: Date): string {
  return toStoredTimestamp(d.toISOString());         // 2026-09-11T17:25:01.155Z
}

/**
 * Assign one output key.
 *
 * `__proto__` is the one name that cannot be written with plain assignment: it
 * runs Object.prototype's setter instead of creating a property, so the column
 * would vanish from the JSON body (and, for an object value, silently re-prototype
 * the row). PostgREST hands `select=__proto__:file_type` back as an ordinary key,
 * and select aliases come straight off the wire — the client, not this codebase,
 * picks that name. Kept as a one-string compare so the normal path stays a plain
 * assignment on every column of every row.
 */
function setKey(out: Record<string, unknown>, key: string, value: unknown): void {
  if (key === "__proto__") {
    Object.defineProperty(out, key, { value, enumerable: true, writable: true, configurable: true });
    return;
  }
  out[key] = value;
}

/**
 * The key this select item comes back under. PostgREST answers with the alias
 * when there is one (`cv_langs:cv_draft->langs` → `cv_langs`) and otherwise
 * with the column — or, for a bare arrow select, the last KEY in the path,
 * skipping array indexes (Plan.hs lastJsonKey): `cv_draft->langs->0` is
 * `langs`, and `cv_draft->0` is `cv_draft`. Taking the literal last segment put
 * the value under `0`, where no caller reading `row.langs` would find it.
 *
 * The alias is NOT an identifier this codebase controls: it is whatever the
 * client put in `?select=`, and parseRequest only validates the *column* half
 * against the registry. So whoever emits SQL from this string must quote it and
 * double any `"` inside (buildSql's `qi()` does) — never interpolate it raw.
 */
export function selectOutputKey(item: SelectItem): string {
  if (item.alias !== undefined) return item.alias;
  for (const op of [...(item.jsonPath ?? [])].reverse()) if ("key" in op) return op.key;
  return item.column;
}

/**
 * The name buildSql() gives item `i` in the SQL, and decodeRows() reads it back
 * under — or null for a star. Kept in one place so the halves cannot disagree.
 *
 * Usually the output key itself. Two cases can't use it: an arrow item fetches
 * the WHOLE column (the path is walked in JavaScript, see jsonPathValue), and a
 * list with a star in it holds every column under its own name, which an alias
 * like `value:key` would collide with in D1's row object. Those get a positional
 * name no select can spell — an alias can't contain `:`, nor `$`-suffixed digits
 * after a registry column.
 */
export function selectSqlKey(select: SelectItem[], i: number): string | null {
  const item = select[i];
  if (item.column === "*") return null;
  if (item.jsonPath) return `json$${i}`;
  return select.some((s) => s.column === "*") ? `sel$${i}` : selectOutputKey(item);
}

/** The positional names above, plus read.ts's rowid: never part of a response. */
const INTERNAL_KEY = /^(?:(?:json|sel)\$\d+|rowid\$)$/;

/* ────────────────────────────── decoding ────────────────────────────── */

/**
 * One SQLite value → the PostgREST/JSON value for a column of type `pg`.
 * `pg` is undefined for a column the registry does not know (a table added
 * since d1/types.json was generated); such a value is passed through untouched
 * rather than guessed at, so nothing is corrupted silently.
 */
export function decodeValue(value: unknown, pg: PgType | undefined): unknown {
  if (value === null || value === undefined) return null;

  switch (pg) {
    case "boolean": {
      // Stored 0/1 (d1/schema.sql pins that with a CHECK … IN (0,1)), but the
      // string forms are accepted too so a hand-run `UPDATE … SET x='true'` in
      // the D1 console cannot turn a flag into a truthy string downstream.
      if (typeof value === "boolean") return value;
      if (typeof value === "number") return value !== 0;
      if (typeof value === "string") {
        const s = value.trim().toLowerCase();
        if (BOOL_TRUE.has(s)) return true;
        if (BOOL_FALSE.has(s)) return false;
      }
      return value; // unrecognisable — surface it instead of inventing `false`
    }

    case "integer":
    case "bigint":
    case "numeric": {
      // PostgREST serialises all three as JSON numbers (bigint included — every
      // bigint here is a small surrogate id, far inside 2^53).
      if (typeof value === "number") return value;
      const n = Number(value);
      return Number.isFinite(n) ? n : value;
    }

    case "jsonb":
    case "text[]":
    case "uuid[]":
      return parseJsonText(value);

    // uuid / text / date / timestamptz: TEXT in, TEXT out. The import wrote
    // exactly what PostgREST returned, so the format already matches Postgres
    // and re-formatting could only damage it.
    default:
      return value;
  }
}

/**
 * JSON text → value. A row that is NOT valid JSON is returned as the raw
 * string instead of throwing: one bad row (a `text[]` still holding a Postgres
 * array literal `{a,b}` because it was inserted outside the importer, say)
 * must degrade to a visibly odd value on one field, never a 500 that takes the
 * whole page with it.
 */
function parseJsonText(value: unknown): unknown {
  if (typeof value !== "string") return value; // already a number/boolean from SQLite
  try {
    return JSON.parse(value);
  } catch {
    return value;
  }
}

/* ───────────────────────────── arrow selects ───────────────────────────── */

const isJsonObject = (v: unknown): v is Record<string, unknown> =>
  typeof v === "object" && v !== null && !Array.isArray(v);

/**
 * The value behind `col->a->0->>b`, walked the way Postgres walks it.
 *
 * SQLite's json_extract was the wrong tool three ways over: it hands a JSON
 * string back unquoted, so the decoder's JSON.parse turned `"51000"` into the
 * number 51000; it cannot tell `->` from `->>`; and it raises "malformed JSON" on
 * a column that isn't JSON, which failed the whole query with a 500. So buildSql
 * fetches the column and this walks it:
 *
 *  • the start is `to_jsonb(col)` — PostgREST wraps every non-json column that
 *    way (Plan.hs cfToJson), so `first_name->a` is null, not an error, and a
 *    boolean/number/timestamp becomes its JSON value;
 *  • `->key` finds a member of an object, and nothing else;
 *  • `->n` finds an element of an array, counting from the end when negative —
 *    and Postgres stores a JSON scalar as a one-element array, so `->0` and
 *    `->-1` on a scalar return the scalar itself (live: `position->0` is 8);
 *  • `->>` (always the last step; a later one is refused in parseRequest, as
 *    Postgres refuses `text -> …`) returns TEXT: a string as itself, JSON null
 *    as null, anything else in jsonb's own text form — `"[\"a\", \"b\"]"`.
 *
 * A step that finds nothing is SQL NULL, which PostgREST serialises as null.
 */
export function jsonPathValue(raw: unknown, pg: PgType | undefined, ops: readonly JsonOp[]): unknown {
  if (raw === null || raw === undefined) return null;
  let v: unknown = decodeValue(raw, pg);
  for (const op of ops) {
    if ("key" in op) {
      if (!isJsonObject(v) || !Object.prototype.hasOwnProperty.call(v, op.key)) return null;
      v = v[op.key];
    } else {
      if (isJsonObject(v)) return null;
      const elements = Array.isArray(v) ? v : [v];
      const at = op.index < 0 ? op.index + elements.length : op.index;
      if (at < 0 || at >= elements.length) return null;
      v = elements[at];
    }
    if (op.arrow === "->>") return v === null ? null : typeof v === "string" ? v : jsonbText(v);
  }
  return v;
}

/** jsonb's key order: shorter UTF-8 first, then bytewise (lengthCompareJsonbStringValue). */
function jsonbKeyOrder(a: string, b: string): number {
  const x = new TextEncoder().encode(a);
  const y = new TextEncoder().encode(b);
  if (x.length !== y.length) return x.length - y.length;
  for (let i = 0; i < x.length; i++) if (x[i] !== y[i]) return x[i] - y[i];
  return 0;
}

/**
 * A number as Postgres' numeric prints it: never in exponent form. JavaScript
 * writes 1e-7 and 1e+21 where a jsonb text value holds 0.0000001 and 1 followed
 * by 21 zeros.
 */
function numericText(n: number): string {
  const s = String(n);
  const m = /^(-?)(\d)(?:\.(\d+))?e([+-]\d+)$/.exec(s);
  if (!m) return s;
  const [, sign, int, frac = "", exp] = m;
  const digits = int + frac;
  const point = 1 + Number(exp);
  if (point <= 0) return `${sign}0.${"0".repeat(-point)}${digits}`;
  if (point >= digits.length) return `${sign}${digits}${"0".repeat(point - digits.length)}`;
  return `${sign}${digits.slice(0, point)}.${digits.slice(point)}`;
}

/**
 * A JSON value in jsonb's text output (JsonbToCString) — what `->>` returns for
 * an object or array: `, ` between elements, `: ` after a key, keys in jsonb's
 * stored order. JSON.stringify's string escaping is escape_json's.
 */
export function jsonbText(v: unknown): string {
  if (v === null || v === undefined) return "null";
  if (typeof v === "string") return JSON.stringify(v);
  if (typeof v === "number") return numericText(v);
  if (typeof v === "boolean") return v ? "true" : "false";
  if (Array.isArray(v)) return `[${v.map(jsonbText).join(", ")}]`;
  const obj = v as Record<string, unknown>;
  return `{${Object.keys(obj).sort(jsonbKeyOrder).map((k) => `${JSON.stringify(k)}: ${jsonbText(obj[k])}`).join(", ")}}`;
}

/** Every registry column of a `*`, in table order, then any column D1 has that the registry hasn't caught up with. */
function starColumns(out: Record<string, unknown>, row: Record<string, unknown>, columns: Registry[string]["columns"] | undefined): void {
  for (const col of columns ? Object.keys(columns) : []) {
    if (Object.prototype.hasOwnProperty.call(row, col)) setKey(out, col, decodeValue(row[col], columns![col].pg));
  }
  // Dropping an unknown column would lose real data; passing it through untyped
  // is the honest fallback (a stale types.json must not eat a new column).
  // hasOwnProperty, not `in`: `"constructor" in {}` is true, and a column by
  // that name would be silently dropped.
  for (const key of Object.keys(row)) {
    if (INTERNAL_KEY.test(key) || (columns && Object.prototype.hasOwnProperty.call(columns, key))) continue;
    if (!Object.prototype.hasOwnProperty.call(out, key)) setKey(out, key, row[key] === undefined ? null : row[key]);
  }
}

/**
 * D1 result rows → PostgREST response rows.
 *
 * Besides types this fixes *key order*: PostgREST returns columns in the order
 * they were asked for (and, for `*`, in the table's own column order), and the
 * response body is JSON, where key order is observable. Rebuilding each row in
 * that order keeps the wire bytes identical to Supabase's, which matters for
 * anything that snapshots or hashes a response — d1/parity-check.mjs included.
 */
export function decodeRows(
  rows: Record<string, unknown>[],
  intent: QueryIntent,
  registry: Registry,
): Record<string, unknown>[] {
  const columns = registry[intent.table]?.columns;
  const select = intent.select; // hoisted: narrowing a parameter's property is lost inside the row callbacks

  // An empty list means every column, exactly as `?select=` does in PostgREST —
  // which is how a mutation with a bare `.select()` arrives.
  if (select === "*" || select.length === 0) {
    return rows.map((row) => {
      const out: Record<string, unknown> = {};
      starColumns(out, row, columns);
      return out;
    });
  }

  const hasStar = select.some((item) => item.column === "*");
  return rows.map((row) => {
    const out: Record<string, unknown> = {};
    select.forEach((item, i) => {
      if (item.column === "*") { starColumns(out, row, columns); return; }
      const key = selectOutputKey(item);
      const sqlKey = selectSqlKey(select, i)!;
      // Read under the name buildSql gave it, falling back to the source column
      // so either aliasing convention works — but only for a plain column in a
      // star-free list. An arrow item gets NO such fallback: `cv_draft` in the row
      // is the whole draft, not the extracted `langs`, so falling back there would
      // hand `germanSummary({langs})` an entire (PII-heavy) CV document instead of
      // the null PostgREST returns. A key present nowhere becomes null rather than
      // an absent property, so the row shape stays stable — both for
      // `rows.map(r => r.foo)` and for `p.cv_langs !== undefined`, which
      // app/api/portal/admin/b2-overview/route.ts:69 branches on.
      const raw = Object.prototype.hasOwnProperty.call(row, sqlKey)
        ? row[sqlKey]
        : !item.jsonPath && !hasStar && Object.prototype.hasOwnProperty.call(row, item.column)
          ? row[item.column]
          : null;
      const pg = columns?.[item.column]?.pg;
      // A key written twice (`key,*`) keeps its first position and its last
      // value — exactly what JSON.parse makes of PostgREST's duplicate keys.
      setKey(out, key, item.jsonPath ? jsonPathValue(raw, pg, item.jsonPath) : decodeValue(raw, pg));
    });
    return out;
  });
}

/* ────────────────────────────── encoding ────────────────────────────── */

/**
 * A JS value from a call site → a D1 bound parameter.
 *
 * Mirrors d1/export-data.mjs `encodeParam()` exactly — that function wrote every
 * row now in D1, so anything else here would compare against the stored data
 * wrongly. Used by buildSql() for INSERT/UPDATE/UPSERT payloads and for filter
 * operands alike; for `in` it is called once per element, and `like`/`ilike`
 * patterns are text and should be bound directly rather than routed through a
 * column's type.
 *
 * D1 binds null / number / string / boolean; objects must be serialised here or
 * they arrive as `[object Object]`.
 */
export function encodeValue(value: unknown, pg: PgType | undefined): unknown {
  if (value === null || value === undefined) return null;
  // An Invalid Date throws inside toISOString(), and nothing in this module may
  // throw — one bad value must cost one field, never the whole request. null is
  // also what would really have reached Supabase: supabase-js JSON-stringifies
  // write payloads, and `JSON.stringify(new Date(NaN))` is `null`.
  if (value instanceof Date && Number.isNaN(value.getTime())) return null;

  switch (pg) {
    case "boolean": {
      if (typeof value === "boolean") return value ? 1 : 0;
      if (typeof value === "number") return value !== 0 ? 1 : 0;
      if (typeof value === "string") {
        const s = value.trim().toLowerCase();
        if (BOOL_TRUE.has(s)) return 1;
        if (BOOL_FALSE.has(s)) return 0;
      }
      return value; // not a boolean literal — let the comparison simply not match
    }

    case "integer":
    case "bigint":
    case "numeric": {
      // A bigint past 2^53 arrives as its decimal string (pgInput's intIn keeps
      // it that way on purpose): Number() would round it onto a neighbouring id,
      // while SQLite's INTEGER affinity reads the string exactly.
      if (pg !== "numeric" && typeof value === "string" && /^-?\d+$/.test(value) && !Number.isSafeInteger(Number(value))) return value;
      const n = typeof value === "number" ? value : Number(value);
      // Non-finite can neither be stored nor compared; export-data.mjs mapped it
      // to NULL and so do we. A non-numeric string is left alone so a filter on
      // garbage fails to match instead of becoming a silent `= NULL`.
      if (Number.isFinite(n)) return n;
      return typeof value === "number" ? null : value;
    }

    case "jsonb":
    case "text[]":
    case "uuid[]":
      // Unconditional stringify, matching export-data.mjs: through supabase-js a
      // JS string bound to a jsonb column becomes a JSON *string*, so `"abc"` —
      // quotes included — is the faithful encoding, not `abc`.
      return JSON.stringify(value);

    case "timestamptz": {
      if (value instanceof Date) return dateToStoredTimestamp(value);
      if (typeof value === "string" && ISO_INSTANT.test(value)) {
        // `2026-09-11T17:25:01.155Z` and `…+00:00` are the same instant to
        // Postgres but different TEXT to SQLite, and every stored row uses the
        // offset form, so a `Z` value is re-rendered the way PostgREST would have
        // rendered it (offset + trimmed fraction).
        //
        // A value that ALREADY carries an offset is returned byte-for-byte: it is
        // almost always a timestamp the caller read back out of a row
        // (`.eq("created_at", row.created_at)`), and the copy holds two fraction
        // widths — the imported rows are Postgres-trimmed (`.155`) while rows D1
        // writes from its own column DEFAULT are 6-digit (`.155000`, see
        // d1/gen-schema.mjs `nowExpr`). Normalising here would break equality
        // against whichever of the two we normalised away from.
        return value.endsWith("Z") ? toStoredTimestamp(value) : value;
      }
      return typeof value === "string" ? value : String(value);
    }

    case "date": {
      if (value instanceof Date) return value.toISOString().slice(0, 10);
      if (typeof value === "string" && ISO_INSTANT.test(value)) return value.slice(0, 10);
      return typeof value === "string" ? value : String(value);
    }

    // uuid / text — and the unknown-column case, where the registry has no type.
    default: {
      if (typeof value === "string") return value;
      if (pg === "text" || pg === "uuid") {
        // Postgres reads a JSON number or boolean into a text column as its
        // literal: `5`, `true`. Bound as the JS value, D1 stored `5.0` (the HTTP
        // API binds every number as a REAL, and TEXT affinity prints a REAL that
        // way) and `1.0` — strings no filter written against Postgres' spelling
        // would ever match.
        if (typeof value === "boolean") return value ? "true" : "false";
        if (typeof value === "number") return Number.isFinite(value) ? JSON.stringify(value) : null;
      }
      if (typeof value === "boolean") return value ? 1 : 0;   // unknown column: SQLite has no boolean
      if (typeof value === "number") return Number.isFinite(value) ? value : null;
      if (value instanceof Date) return dateToStoredTimestamp(value);
      // An object on a text column is a caller bug either way; JSON is at least
      // readable and reversible, unlike String({}) → "[object Object]".
      if (typeof value === "object") return JSON.stringify(value);
      return String(value);
    }
  }
}
