/**
 * Value codec for the PostgREST→D1 adapter: SQLite values ⇄ what the 1,261
 * existing `.from(...)` call sites already receive from Supabase.
 *
 *   D1 row  → decodeRows()  → response body   (what supabase-js hands the caller)
 *   JS value → encodeValue() → bound parameter (what buildSql() sends to D1)
 *
 * The two halves must be exact inverses, because the D1 copy was written by
 * d1/export-data.mjs `encodeParam()` reading live PostgREST output. Whatever
 * that function did on the way IN, decodeValue() has to undo on the way OUT, or
 * a candidate's `documents.uploaded_by_admin` comes back as the number 1 and
 * `if (doc.uploaded_by_admin === true)` silently stops matching. Hence:
 *
 *   Postgres type   D1 storage (d1/schema.sql)   what callers expect back
 *   ─────────────   ──────────────────────────   ────────────────────────
 *   boolean         INTEGER 0 / 1                true / false
 *   integer/bigint  INTEGER                      number
 *   numeric         REAL                         number
 *   jsonb           TEXT holding JSON            parsed object/array/scalar
 *   text[] uuid[]   TEXT holding a JSON array    parsed array
 *   uuid text date  TEXT                         the same string
 *   timestamptz     TEXT, already in Postgres's  the same string
 *                   `…T17:25:01.155+00:00` form
 *
 * Everything here is pure: no D1 client, no fetch, no globals. The registry
 * (d1/types.json, regenerated by d1/gen-schema.mjs) is the only type source —
 * SQLite's own column affinity cannot tell a boolean from an integer, nor JSON
 * text from ordinary text, so guessing from the value is never an option.
 */
import type { PgType, QueryIntent, Registry, SelectItem } from "./types";

/* ────────────────────────────── helpers ────────────────────────────── */

/** Postgres boolean input literals (`SELECT 'yes'::boolean` works). */
const BOOL_TRUE = new Set(["true", "t", "yes", "y", "on", "1"]);
const BOOL_FALSE = new Set(["false", "f", "no", "n", "off", "0"]);

/** A full ISO-8601 instant — date, time and a zone. Partial values like the
 *  `"2026-09-01"` people pass to `.gte("created_at", …)` deliberately do NOT
 *  match: a bare date is already a correct lexical lower bound for that day. */
const ISO_INSTANT = /^\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})$/;

/**
 * An ISO UTC instant → the TEXT PostgREST would have produced for it: a `+00:00`
 * offset instead of `Z`, and Postgres's trailing-zero trimming of the fraction.
 *
 * Postgres prints `17:25:01.15+00:00` for 150 ms and `17:25:01+00:00` for a whole
 * second — it never pads. The stored rows came from PostgREST, so a value we
 * build has to compare against them as TEXT: `.150+00:00` is the same instant as
 * the `.15+00:00` sitting in the table but a different string, so `.eq()` would
 * miss it and `.gte()` would sort it on the wrong side. `new Date().toISOString()`
 * always emits exactly three fraction digits, so ~10% of the timestamps the call
 * sites hand us (`created_at: new Date().toISOString()`, lib/assistantWrites.ts:190)
 * end in a zero and need this.
 */
function toStoredTimestamp(isoUtc: string): string {
  const body = isoUtc.endsWith("Z") ? isoUtc.slice(0, -1) : isoUtc;
  return `${body.replace(/\.(\d+)$/, (_m, frac: string) => {
    const trimmed = frac.replace(/0+$/, "");
    return trimmed ? `.${trimmed}` : "";
  })}+00:00`;
}

/** The same, for a Date — the only shape that reaches us without a `Z` string. */
function dateToStoredTimestamp(d: Date): string {
  return toStoredTimestamp(d.toISOString());         // 2026-09-11T17:25:01.155Z
}

/**
 * Assign one output key.
 *
 * `__proto__` is the one name that cannot be written with plain assignment: it
 * runs Object.prototype's setter instead of creating a property, so the column
 * would vanish from the JSON body (and, for an object value, silently re-prototype
 * the row). PostgREST hands `select=__proto__:file_type` back as an ordinary key,
 * and select aliases come straight off the wire — the client, not this codebase,
 * picks that name. Kept as a one-string compare so the normal path stays a plain
 * assignment on every column of every row.
 */
function setKey(out: Record<string, unknown>, key: string, value: unknown): void {
  if (key === "__proto__") {
    Object.defineProperty(out, key, { value, enumerable: true, writable: true, configurable: true });
    return;
  }
  out[key] = value;
}

/**
 * The key this select item comes back under. PostgREST answers with the alias
 * when there is one (`cv_langs:cv_draft->langs` → `cv_langs`) and otherwise
 * with the column — or, for a bare arrow select, the last JSON key it walked.
 * Exported so buildSql() can emit the matching `AS "<key>"` and the two halves
 * cannot drift apart.
 *
 * The alias is NOT an identifier this codebase controls: it is whatever the
 * client put in `?select=`, and parseRequest only validates the *column* half
 * against the registry. So whoever emits SQL from this string must quote it and
 * double any `"` inside (buildSql's `qi()` does) — never interpolate it raw.
 */
export function selectOutputKey(item: SelectItem): string {
  if (item.alias) return item.alias;
  if (item.jsonPath) {
    const parts = item.jsonPath.split(/->>?|\./).filter(Boolean);
    return parts[parts.length - 1] ?? item.column;
  }
  return item.column;
}

/* ────────────────────────────── decoding ────────────────────────────── */

/**
 * One SQLite value → the PostgREST/JSON value for a column of type `pg`.
 * `pg` is undefined for a column the registry does not know (a table added
 * since d1/types.json was generated); such a value is passed through untouched
 * rather than guessed at, so nothing is corrupted silently.
 */
export function decodeValue(value: unknown, pg: PgType | undefined): unknown {
  if (value === null || value === undefined) return null;

  switch (pg) {
    case "boolean": {
      // Stored 0/1 (d1/schema.sql pins that with a CHECK … IN (0,1)), but the
      // string forms are accepted too so a hand-run `UPDATE … SET x='true'` in
      // the D1 console cannot turn a flag into a truthy string downstream.
      if (typeof value === "boolean") return value;
      if (typeof value === "number") return value !== 0;
      if (typeof value === "string") {
        const s = value.trim().toLowerCase();
        if (BOOL_TRUE.has(s)) return true;
        if (BOOL_FALSE.has(s)) return false;
      }
      return value; // unrecognisable — surface it instead of inventing `false`
    }

    case "integer":
    case "bigint":
    case "numeric": {
      // PostgREST serialises all three as JSON numbers (bigint included — every
      // bigint here is a small surrogate id, far inside 2^53).
      if (typeof value === "number") return value;
      const n = Number(value);
      return Number.isFinite(n) ? n : value;
    }

    case "jsonb":
    case "text[]":
    case "uuid[]":
      return parseJsonText(value);

    // uuid / text / date / timestamptz: TEXT in, TEXT out. The import wrote
    // exactly what PostgREST returned, so the format already matches Postgres
    // and re-formatting could only damage it.
    default:
      return value;
  }
}

/**
 * JSON text → value. A row that is NOT valid JSON is returned as the raw
 * string instead of throwing: one bad row (a `text[]` still holding a Postgres
 * array literal `{a,b}` because it was inserted outside the importer, say)
 * must degrade to a visibly odd value on one field, never a 500 that takes the
 * whole page with it.
 */
function parseJsonText(value: unknown): unknown {
  if (typeof value !== "string") return value; // already a number/boolean from SQLite
  try {
    return JSON.parse(value);
  } catch {
    return value;
  }
}

/**
 * The value behind `alias:col->key`.
 *
 * Which SQLite form arrives depends on how buildSql() extracts it, and both are
 * handled because both are defensible:
 *   `cv_draft -> '$.langs'`        → JSON text for everything (strings quoted)
 *   `json_extract(cv_draft,'$.langs')` → JSON text for objects/arrays, but a raw
 *                                    SQL value for scalars
 * Objects and arrays parse either way. A raw scalar string fails to parse and
 * comes back as itself, which is what PostgREST's `->>` would have given.
 * (`->` is the closer match to PostgREST's jsonb-returning `->`; see the report.)
 * A missing path is SQL NULL in SQLite and JSON null in Postgres — both null.
 */
function decodeJsonPathValue(value: unknown): unknown {
  if (value === null || value === undefined) return null;
  return parseJsonText(value);
}

/**
 * D1 result rows → PostgREST response rows.
 *
 * Besides types this fixes *key order*: PostgREST returns columns in the order
 * they were asked for (and, for `*`, in the table's own column order), and the
 * response body is JSON, where key order is observable. Rebuilding each row in
 * that order keeps the wire bytes identical to Supabase's, which matters for
 * anything that snapshots or hashes a response — d1/parity-check.mjs included.
 */
export function decodeRows(
  rows: Record<string, unknown>[],
  intent: QueryIntent,
  registry: Registry,
): Record<string, unknown>[] {
  const columns = registry[intent.table]?.columns;
  const select = intent.select; // hoisted: narrowing a parameter's property is lost inside the row callbacks

  // An empty list means every column, exactly as `?select=` does in PostgREST —
  // which is how a mutation with a bare `.select()` arrives.
  if (select === "*" || select.length === 0) {
    const known = columns ? Object.keys(columns) : [];
    return rows.map((row) => {
      const out: Record<string, unknown> = {};
      // Registry order first…
      for (const col of known) {
        if (Object.prototype.hasOwnProperty.call(row, col)) setKey(out, col, decodeValue(row[col], columns![col].pg));
      }
      // …then anything D1 returned that the registry has not caught up with.
      // Dropping it would lose real data; passing it through untyped is the
      // honest fallback (a stale types.json must not eat a new column).
      // hasOwnProperty, not `in`: `"constructor" in {}` is true, and a column by
      // that name would be silently dropped.
      for (const key of Object.keys(row)) {
        if (!Object.prototype.hasOwnProperty.call(out, key)) setKey(out, key, row[key] === undefined ? null : row[key]);
      }
      return out;
    });
  }

  return rows.map((row) => {
    const out: Record<string, unknown> = {};
    for (const item of select) {
      const key = selectOutputKey(item);
      // Read under the alias first (buildSql emits `AS "<key>"`), falling back to
      // the source column name so either aliasing convention works — but only for
      // a plain column. A json-path item gets NO such fallback: `cv_draft` in the
      // row is the whole draft, not the extracted `langs`, so falling back there
      // would hand `germanSummary({langs})` an entire (PII-heavy) CV document
      // instead of the null PostgREST returns. A key present nowhere becomes null
      // rather than an absent property, so the row shape stays stable — both for
      // `rows.map(r => r.foo)` and for `p.cv_langs !== undefined`, which
      // app/api/portal/admin/b2-overview/route.ts:69 branches on.
      const raw = Object.prototype.hasOwnProperty.call(row, key)
        ? row[key]
        : !item.jsonPath && Object.prototype.hasOwnProperty.call(row, item.column)
          ? row[item.column]
          : null;
      setKey(out, key, item.jsonPath
        ? decodeJsonPathValue(raw)
        : decodeValue(raw, columns?.[item.column]?.pg));
    }
    return out;
  });
}

/* ────────────────────────────── encoding ────────────────────────────── */

/**
 * A JS value from a call site → a D1 bound parameter.
 *
 * Mirrors d1/export-data.mjs `encodeParam()` exactly — that function wrote every
 * row now in D1, so anything else here would compare against the stored data
 * wrongly. Used by buildSql() for INSERT/UPDATE/UPSERT payloads and for filter
 * operands alike; for `in` it is called once per element, and `like`/`ilike`
 * patterns are text and should be bound directly rather than routed through a
 * column's type.
 *
 * D1 binds null / number / string / boolean; objects must be serialised here or
 * they arrive as `[object Object]`.
 */
export function encodeValue(value: unknown, pg: PgType | undefined): unknown {
  if (value === null || value === undefined) return null;
  // An Invalid Date throws inside toISOString(), and nothing in this module may
  // throw — one bad value must cost one field, never the whole request. null is
  // also what would really have reached Supabase: supabase-js JSON-stringifies
  // write payloads, and `JSON.stringify(new Date(NaN))` is `null`.
  if (value instanceof Date && Number.isNaN(value.getTime())) return null;

  switch (pg) {
    case "boolean": {
      if (typeof value === "boolean") return value ? 1 : 0;
      if (typeof value === "number") return value !== 0 ? 1 : 0;
      if (typeof value === "string") {
        const s = value.trim().toLowerCase();
        if (BOOL_TRUE.has(s)) return 1;
        if (BOOL_FALSE.has(s)) return 0;
      }
      return value; // not a boolean literal — let the comparison simply not match
    }

    case "integer":
    case "bigint":
    case "numeric": {
      // A bigint past 2^53 arrives as its decimal string (pgInput's intIn keeps
      // it that way on purpose): Number() would round it onto a neighbouring id,
      // while SQLite's INTEGER affinity reads the string exactly.
      if (pg !== "numeric" && typeof value === "string" && /^-?\d+$/.test(value) && !Number.isSafeInteger(Number(value))) return value;
      const n = typeof value === "number" ? value : Number(value);
      // Non-finite can neither be stored nor compared; export-data.mjs mapped it
      // to NULL and so do we. A non-numeric string is left alone so a filter on
      // garbage fails to match instead of becoming a silent `= NULL`.
      if (Number.isFinite(n)) return n;
      return typeof value === "number" ? null : value;
    }

    case "jsonb":
    case "text[]":
    case "uuid[]":
      // Unconditional stringify, matching export-data.mjs: through supabase-js a
      // JS string bound to a jsonb column becomes a JSON *string*, so `"abc"` —
      // quotes included — is the faithful encoding, not `abc`.
      return JSON.stringify(value);

    case "timestamptz": {
      if (value instanceof Date) return dateToStoredTimestamp(value);
      if (typeof value === "string" && ISO_INSTANT.test(value)) {
        // `2026-09-11T17:25:01.155Z` and `…+00:00` are the same instant to
        // Postgres but different TEXT to SQLite, and every stored row uses the
        // offset form, so a `Z` value is re-rendered the way PostgREST would have
        // rendered it (offset + trimmed fraction).
        //
        // A value that ALREADY carries an offset is returned byte-for-byte: it is
        // almost always a timestamp the caller read back out of a row
        // (`.eq("created_at", row.created_at)`), and the copy holds two fraction
        // widths — the imported rows are Postgres-trimmed (`.155`) while rows D1
        // writes from its own column DEFAULT are 6-digit (`.155000`, see
        // d1/gen-schema.mjs `nowExpr`). Normalising here would break equality
        // against whichever of the two we normalised away from.
        return value.endsWith("Z") ? toStoredTimestamp(value) : value;
      }
      return typeof value === "string" ? value : String(value);
    }

    case "date": {
      if (value instanceof Date) return value.toISOString().slice(0, 10);
      if (typeof value === "string" && ISO_INSTANT.test(value)) return value.slice(0, 10);
      return typeof value === "string" ? value : String(value);
    }

    // uuid / text — and the unknown-column case, where the registry has no type.
    default: {
      if (typeof value === "string") return value;
      if (pg === "text" || pg === "uuid") {
        // Postgres reads a JSON number or boolean into a text column as its
        // literal: `5`, `true`. Bound as the JS value, D1 stored `5.0` (the HTTP
        // API binds every number as a REAL, and TEXT affinity prints a REAL that
        // way) and `1.0` — strings no filter written against Postgres' spelling
        // would ever match.
        if (typeof value === "boolean") return value ? "true" : "false";
        if (typeof value === "number") return Number.isFinite(value) ? JSON.stringify(value) : null;
      }
      if (typeof value === "boolean") return value ? 1 : 0;   // unknown column: SQLite has no boolean
      if (typeof value === "number") return Number.isFinite(value) ? value : null;
      if (value instanceof Date) return dateToStoredTimestamp(value);
      // An object on a text column is a caller bug either way; JSON is at least
      // readable and reversible, unlike String({}) → "[object Object]".
      if (typeof value === "object") return JSON.stringify(value);
      return String(value);
    }
  }
}
