-- GENERATED by d1/gen-schema.mjs from the live Supabase structure snapshots.
-- Do not edit by hand: change the generator (or re-capture the snapshots) and re-run it.

CREATE TABLE IF NOT EXISTS "academy_attendance" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "session_id" TEXT NOT NULL,
  "candidate_user_id" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'absent',
  "joined_at" TEXT,
  "left_at" TEXT,
  "minutes_present" INTEGER,
  "source" TEXT NOT NULL DEFAULT 'auto',
  "recorded_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id"),
  CONSTRAINT "academy_attendance_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "academy_class_sessions" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT "academy_attendance_status_check" CHECK ((status IN ('present', 'late', 'absent', 'excused'))),
  CONSTRAINT "academy_attendance_source_check" CHECK ((source IN ('auto', 'admin', 'self')))
);
CREATE TABLE IF NOT EXISTS "academy_badges" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "key" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "icon" TEXT,
  "points" INTEGER NOT NULL DEFAULT 0,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS "academy_class_sessions" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "cohort_id" TEXT NOT NULL,
  "lesson_id" TEXT,
  "title" TEXT NOT NULL DEFAULT '',
  "level" TEXT NOT NULL DEFAULT 'A1',
  "starts_at" TEXT NOT NULL,
  "ends_at" TEXT,
  "meeting_url" TEXT,
  "meeting_provider" TEXT,
  "external_ref" TEXT,
  "created_by" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id"),
  CONSTRAINT "academy_class_sessions_cohort_id_fkey" FOREIGN KEY ("cohort_id") REFERENCES "academy_cohorts" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT "academy_class_sessions_lesson_id_fkey" FOREIGN KEY ("lesson_id") REFERENCES "academy_lessons" ("id") ON DELETE SET NULL ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "academy_cohort_members" (
  "cohort_id" TEXT NOT NULL,
  "candidate_user_id" TEXT NOT NULL,
  "current_level" TEXT NOT NULL DEFAULT 'A1',
  "status" TEXT NOT NULL DEFAULT 'active',
  "joined_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("cohort_id", "candidate_user_id"),
  CONSTRAINT "academy_cohort_members_cohort_id_fkey" FOREIGN KEY ("cohort_id") REFERENCES "academy_cohorts" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT "academy_cohort_members_status_check" CHECK ((status IN ('active', 'paused', 'dropped', 'graduated')))
);
CREATE TABLE IF NOT EXISTS "academy_cohorts" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "org_id" TEXT,
  "name" TEXT NOT NULL,
  "target_level" TEXT NOT NULL DEFAULT 'B2',
  "starts_on" TEXT,
  "ends_on" TEXT,
  "status" TEXT NOT NULL DEFAULT 'active',
  "created_by" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id"),
  CONSTRAINT "academy_cohorts_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON DELETE SET NULL ON UPDATE NO ACTION,
  CONSTRAINT "academy_cohorts_status_check" CHECK ((status IN ('active', 'archived')))
);
CREATE TABLE IF NOT EXISTS "academy_lessons" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "org_id" TEXT,
  "level" TEXT NOT NULL DEFAULT 'A1',
  "title" TEXT NOT NULL DEFAULT '',
  "body" TEXT NOT NULL DEFAULT '{}' CHECK ("body" IS NULL OR json_valid("body")),
  "media_url" TEXT,
  "position" INTEGER NOT NULL DEFAULT 0,
  "published" INTEGER NOT NULL DEFAULT 0 CHECK ("published" IN (0, 1)),
  "created_by" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id"),
  CONSTRAINT "academy_lessons_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON DELETE SET NULL ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "academy_point_events" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "candidate_user_id" TEXT NOT NULL,
  "cohort_id" TEXT,
  "type" TEXT NOT NULL,
  "points" INTEGER NOT NULL,
  "source_kind" TEXT,
  "source_id" TEXT,
  "meta" TEXT NOT NULL DEFAULT '{}' CHECK ("meta" IS NULL OR json_valid("meta")),
  "note" TEXT,
  "created_by" TEXT NOT NULL DEFAULT 'system',
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id"),
  CONSTRAINT "academy_point_events_cohort_id_fkey" FOREIGN KEY ("cohort_id") REFERENCES "academy_cohorts" ("id") ON DELETE SET NULL ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "academy_quizzes" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "cohort_id" TEXT,
  "lesson_id" TEXT,
  "level" TEXT NOT NULL DEFAULT 'A1',
  "title" TEXT NOT NULL DEFAULT '',
  "kind" TEXT NOT NULL DEFAULT 'quiz',
  "questions" TEXT NOT NULL DEFAULT '[]' CHECK ("questions" IS NULL OR json_valid("questions")),
  "pass_score" INTEGER NOT NULL DEFAULT 60,
  "points_award" INTEGER NOT NULL DEFAULT 0,
  "due_at" TEXT,
  "published" INTEGER NOT NULL DEFAULT 0 CHECK ("published" IN (0, 1)),
  "created_by" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id"),
  CONSTRAINT "academy_quizzes_cohort_id_fkey" FOREIGN KEY ("cohort_id") REFERENCES "academy_cohorts" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT "academy_quizzes_lesson_id_fkey" FOREIGN KEY ("lesson_id") REFERENCES "academy_lessons" ("id") ON DELETE SET NULL ON UPDATE NO ACTION,
  CONSTRAINT "academy_quizzes_kind_check" CHECK ((kind IN ('quiz', 'homework', 'mock_exam')))
);
CREATE TABLE IF NOT EXISTS "academy_settings" (
  "id" INTEGER NOT NULL DEFAULT 1 CHECK ("id" IN (0, 1)),
  "masked_all" INTEGER NOT NULL DEFAULT 1 CHECK ("masked_all" IN (0, 1)),
  "updated_by" TEXT,
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id"),
  CONSTRAINT "academy_settings_single_row" CHECK ((id = 1))
);
CREATE TABLE IF NOT EXISTS "academy_student_badges" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "candidate_user_id" TEXT NOT NULL,
  "badge_id" TEXT NOT NULL,
  "awarded_by" TEXT NOT NULL DEFAULT 'system',
  "awarded_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id"),
  CONSTRAINT "academy_student_badges_badge_id_fkey" FOREIGN KEY ("badge_id") REFERENCES "academy_badges" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "academy_submissions" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "quiz_id" TEXT NOT NULL,
  "candidate_user_id" TEXT NOT NULL,
  "answers" TEXT NOT NULL DEFAULT '[]' CHECK ("answers" IS NULL OR json_valid("answers")),
  "score" REAL,
  "passed" INTEGER CHECK ("passed" IN (0, 1)),
  "on_time" INTEGER CHECK ("on_time" IN (0, 1)),
  "submitted_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "graded_at" TEXT,
  PRIMARY KEY ("id"),
  CONSTRAINT "academy_submissions_quiz_id_fkey" FOREIGN KEY ("quiz_id") REFERENCES "academy_quizzes" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "academy_tab_access" (
  "user_id" TEXT NOT NULL,
  "visible" INTEGER NOT NULL CHECK ("visible" IN (0, 1)),
  "updated_by" TEXT,
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("user_id")
);
CREATE TABLE IF NOT EXISTS "admin_checklist_items" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "scope" TEXT NOT NULL,
  "owner_email" TEXT,
  "org_id" TEXT,
  "text" TEXT NOT NULL,
  "done" INTEGER NOT NULL DEFAULT 0 CHECK ("done" IN (0, 1)),
  "position" INTEGER NOT NULL DEFAULT 0,
  "created_by" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id"),
  CONSTRAINT "admin_checklist_items_scope_check" CHECK ((scope IN ('personal', 'shared', 'shared_hq')))
);
CREATE TABLE IF NOT EXISTS "admin_notifications" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "type" TEXT NOT NULL,
  "user_name" TEXT NOT NULL DEFAULT '',
  "user_email" TEXT NOT NULL DEFAULT '',
  "doc_type" TEXT,
  "doc_name" TEXT,
  "read" INTEGER NOT NULL DEFAULT 0 CHECK ("read" IN (0, 1)),
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id"),
  CONSTRAINT "admin_notifications_type_check" CHECK ((type IN ('signup', 'upload', 'doc-signed', 'doc-uploaded', 'org-join', 'org-request')))
);
CREATE TABLE IF NOT EXISTS "admin_signatures" (
  "admin_email" TEXT NOT NULL,
  "signature" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("admin_email")
);
CREATE TABLE IF NOT EXISTS "affiliate_earnings" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "affiliate_id" TEXT NOT NULL,
  "candidate_user_id" TEXT NOT NULL,
  "amount_eur" REAL NOT NULL DEFAULT 0,
  "status" TEXT NOT NULL DEFAULT 'owed',
  "placed_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "paid_at" TEXT,
  "note" TEXT,
  PRIMARY KEY ("id"),
  CONSTRAINT "affiliate_earnings_affiliate_id_fkey" FOREIGN KEY ("affiliate_id") REFERENCES "affiliates" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "affiliates" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "code" TEXT NOT NULL,
  "dash_token_hash" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "email" TEXT,
  "phone" TEXT,
  "user_id" TEXT,
  "commission_eur" REAL NOT NULL DEFAULT 0,
  "currency" TEXT NOT NULL DEFAULT 'EUR',
  "active" INTEGER NOT NULL DEFAULT 1 CHECK ("active" IN (0, 1)),
  "clicks" INTEGER NOT NULL DEFAULT 0,
  "notes" TEXT,
  "created_by" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "terms_accepted_at" TEXT,
  "terms_version" TEXT,
  PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS "agencies" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "name" TEXT NOT NULL,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS "agency_profiles" (
  "user_id" TEXT NOT NULL,
  "firma" TEXT,
  "strasse" TEXT,
  "hausnummer" TEXT,
  "plz" TEXT,
  "ort" TEXT,
  "kontaktperson" TEXT,
  "telefon" TEXT,
  "email" TEXT,
  "telefax" TEXT,
  "betriebsnummer" TEXT,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "updated_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("user_id")
);
CREATE TABLE IF NOT EXISTS "app_settings" (
  "key" TEXT NOT NULL,
  "value" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("key")
);
CREATE TABLE IF NOT EXISTS "assistant_chat_summary" (
  "owner_user_id" TEXT NOT NULL,
  "summary" TEXT NOT NULL DEFAULT '',
  "summarized_through" TEXT,
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("owner_user_id")
);
CREATE TABLE IF NOT EXISTS "assistant_chat_turns" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "owner_user_id" TEXT NOT NULL,
  "role" TEXT NOT NULL,
  "content" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  CONSTRAINT "assistant_chat_turns_role_check" CHECK ((role IN ('user', 'assistant')))
);
CREATE TABLE IF NOT EXISTS "assistant_commitments" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "owner_user_id" TEXT NOT NULL,
  "who_email" TEXT NOT NULL,
  "who_name" TEXT,
  "what" TEXT NOT NULL,
  "due_at" TEXT,
  "promised_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "source_message_id" TEXT NOT NULL DEFAULT '',
  "source_subject" TEXT,
  "status" TEXT NOT NULL DEFAULT 'open',
  "last_nudge_at" TEXT,
  "nudge_count" INTEGER NOT NULL DEFAULT 0,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  CONSTRAINT "assistant_commitments_status_check" CHECK ((status IN ('open', 'done', 'dropped')))
);
CREATE TABLE IF NOT EXISTS "assistant_memory" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "owner_user_id" TEXT NOT NULL,
  "kind" TEXT NOT NULL DEFAULT 'preference',
  "text" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS "assistant_pending_actions" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "owner_user_id" TEXT NOT NULL,
  "tool_name" TEXT NOT NULL,
  "args" TEXT NOT NULL CHECK ("args" IS NULL OR json_valid("args")),
  "candidate_user_id" TEXT,
  "summary" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "expires_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now','+600 seconds') || '000+00:00'),
  PRIMARY KEY ("id"),
  CONSTRAINT "assistant_pending_actions_status_check" CHECK ((status IN ('pending', 'confirmed', 'cancelled', 'expired')))
);
CREATE TABLE IF NOT EXISTS "assistant_reminders" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "owner_user_id" TEXT NOT NULL,
  "text" TEXT NOT NULL,
  "candidate_user_id" TEXT,
  "due_date" TEXT,
  "done" INTEGER NOT NULL DEFAULT 0 CHECK ("done" IN (0, 1)),
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "due_at" TEXT,
  "notified_at" TEXT,
  "remind_count" INTEGER NOT NULL DEFAULT 0,
  "recurrence" TEXT,
  "last_ping_message_id" INTEGER,
  PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS "assistant_sent_emails" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "owner_user_id" TEXT NOT NULL,
  "to_email" TEXT NOT NULL,
  "cc" TEXT,
  "subject" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "candidate_ids" TEXT,
  "doc_ids" TEXT,
  "channel" TEXT,
  "sent_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS "assistant_token_usage" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "model" TEXT,
  "source" TEXT,
  "input_tokens" INTEGER NOT NULL DEFAULT 0,
  "output_tokens" INTEGER NOT NULL DEFAULT 0,
  "cache_read_tokens" INTEGER NOT NULL DEFAULT 0,
  "cache_write_tokens" INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS "automation_settings" (
  "key" TEXT NOT NULL,
  "enabled" INTEGER NOT NULL DEFAULT 1 CHECK ("enabled" IN (0, 1)),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("key")
);
CREATE TABLE IF NOT EXISTS "booking_availability" (
  "id" INTEGER NOT NULL DEFAULT 1 CHECK ("id" IN (0, 1)),
  "week" TEXT NOT NULL DEFAULT '{"1": ["09:00-13:00", "14:00-18:00"], "2": ["09:00-13:00", "14:00-18:00"], "3": ["09:00-13:00", "14:00-18:00"], "4": ["09:00-13:00", "14:00-18:00"], "5": ["09:00-13:00", "14:00-18:00"]}' CHECK ("week" IS NULL OR json_valid("week")),
  "slot_minutes" INTEGER NOT NULL DEFAULT 30,
  "buffer_minutes" INTEGER NOT NULL DEFAULT 0,
  "min_notice_hours" INTEGER NOT NULL DEFAULT 12,
  "horizon_days" INTEGER NOT NULL DEFAULT 14,
  "blackout_dates" TEXT NOT NULL DEFAULT '[]' CHECK ("blackout_dates" IS NULL OR json_valid("blackout_dates")),
  "accepting" INTEGER NOT NULL DEFAULT 1 CHECK ("accepting" IN (0, 1)),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "updated_by" TEXT,
  PRIMARY KEY ("id"),
  CONSTRAINT "booking_availability_slot_minutes_check" CHECK (((slot_minutes >= 5) AND (slot_minutes <= 240))),
  CONSTRAINT "booking_availability_buffer_minutes_check" CHECK (((buffer_minutes >= 0) AND (buffer_minutes <= 120))),
  CONSTRAINT "booking_availability_min_notice_hours_check" CHECK (((min_notice_hours >= 0) AND (min_notice_hours <= 720))),
  CONSTRAINT "booking_availability_horizon_days_check" CHECK (((horizon_days >= 1) AND (horizon_days <= 90))),
  CONSTRAINT "booking_availability_id_check" CHECK (id)
);
CREATE TABLE IF NOT EXISTS "booking_event_types" (
  "slug" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "active" INTEGER NOT NULL DEFAULT 1 CHECK ("active" IN (0, 1)),
  "sort" INTEGER NOT NULL DEFAULT 0,
  "slot_minutes" INTEGER,
  "buffer_minutes" INTEGER,
  "min_notice_hours" INTEGER,
  "horizon_days" INTEGER,
  "title_en" TEXT,
  "title_de" TEXT,
  "title_fr" TEXT,
  "blurb_en" TEXT,
  "blurb_de" TEXT,
  "blurb_fr" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("slug"),
  CONSTRAINT "booking_event_types_kind_check" CHECK ((kind IN ('nurse', 'clinic', 'company'))),
  CONSTRAINT "booking_event_types_slot_minutes_check" CHECK (((slot_minutes IS NULL) OR ((slot_minutes >= 5) AND (slot_minutes <= 240)))),
  CONSTRAINT "booking_event_types_buffer_minutes_check" CHECK (((buffer_minutes IS NULL) OR ((buffer_minutes >= 0) AND (buffer_minutes <= 120)))),
  CONSTRAINT "booking_event_types_min_notice_hours_check" CHECK (((min_notice_hours IS NULL) OR ((min_notice_hours >= 0) AND (min_notice_hours <= 720)))),
  CONSTRAINT "booking_event_types_horizon_days_check" CHECK (((horizon_days IS NULL) OR ((horizon_days >= 1) AND (horizon_days <= 90))))
);
CREATE TABLE IF NOT EXISTS "booking_hosts" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "email" TEXT NOT NULL,
  "display_name" TEXT NOT NULL,
  "calendar_id" TEXT NOT NULL DEFAULT 'primary',
  "user_id" TEXT,
  "active" INTEGER NOT NULL DEFAULT 1 CHECK ("active" IN (0, 1)),
  "sort" INTEGER NOT NULL DEFAULT 0,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00')
);
CREATE TABLE IF NOT EXISTS "bookings" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "kind" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "email" TEXT,
  "phone" TEXT,
  "note" TEXT,
  "company" TEXT,
  "selections" TEXT NOT NULL DEFAULT '{}' CHECK ("selections" IS NULL OR json_valid("selections")),
  "starts_at" TEXT NOT NULL,
  "ends_at" TEXT NOT NULL,
  "calendar_event_id" TEXT,
  "meet_link" TEXT,
  "status" TEXT NOT NULL DEFAULT 'booked',
  "outcome" TEXT,
  "lead_id" TEXT,
  "source" TEXT NOT NULL DEFAULT 'public',
  "created_by" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "manage_token" TEXT,
  "reminded_at" TEXT,
  "rescheduled_from" TEXT,
  "lang" TEXT,
  "host_id" INTEGER,
  "event_type" TEXT,
  CONSTRAINT "bookings_kind_check" CHECK ((kind IN ('nurse', 'clinic', 'company'))),
  CONSTRAINT "bookings_status_check" CHECK ((status IN ('booked', 'held', 'no_show', 'cancelled'))),
  CONSTRAINT "bookings_source_check" CHECK ((source IN ('public', 'admin'))),
  CONSTRAINT "bookings_lang_check" CHECK ((lang IN ('fr', 'en', 'de')))
);
CREATE TABLE IF NOT EXISTS "calendar_events" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "title" TEXT NOT NULL,
  "description" TEXT NOT NULL DEFAULT '',
  "starts_at" TEXT NOT NULL,
  "ends_at" TEXT,
  "image_url" TEXT NOT NULL DEFAULT '',
  "link_url" TEXT NOT NULL DEFAULT '',
  "location" TEXT NOT NULL DEFAULT '',
  "vip_only" INTEGER NOT NULL DEFAULT 0 CHECK ("vip_only" IN (0, 1)),
  "attendee_ids" TEXT NOT NULL DEFAULT '[]' CHECK ("attendee_ids" IS NULL OR json_valid("attendee_ids")),
  "created_by" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS "candidate_journey_items" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "candidate_user_id" TEXT NOT NULL,
  "text" TEXT NOT NULL,
  "owner" TEXT NOT NULL,
  "done" INTEGER NOT NULL DEFAULT 0 CHECK ("done" IN (0, 1)),
  "done_by" TEXT,
  "done_at" TEXT,
  "preset_key" TEXT,
  "position" INTEGER NOT NULL DEFAULT 0,
  "created_by" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "due_date" TEXT,
  "blocked" INTEGER NOT NULL DEFAULT 0 CHECK ("blocked" IN (0, 1)),
  "blocked_reason" TEXT,
  PRIMARY KEY ("id"),
  CONSTRAINT "candidate_journey_items_owner_check" CHECK ((owner IN ('borivon', 'organization', 'candidate')))
);
CREATE TABLE IF NOT EXISTS "candidate_notes" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "candidate_user_id" TEXT NOT NULL,
  "author_email" TEXT NOT NULL,
  "note" TEXT NOT NULL,
  "source" TEXT NOT NULL DEFAULT 'telegram',
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS "candidate_organizations" (
  "candidate_user_id" TEXT NOT NULL,
  "org_id" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'approved',
  "added_by" TEXT NOT NULL DEFAULT 'admin',
  "added_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "approved_at" TEXT,
  "approved_by" TEXT,
  PRIMARY KEY ("candidate_user_id", "org_id"),
  CONSTRAINT "candidate_organizations_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT "candidate_organizations_status_check" CHECK ((status IN ('pending', 'approved', 'rejected'))),
  CONSTRAINT "candidate_organizations_added_by_check" CHECK ((added_by IN ('admin', 'candidate', 'self_signup')))
);
CREATE TABLE IF NOT EXISTS "candidate_pipeline" (
  "user_id" TEXT NOT NULL,
  "interview_link" TEXT,
  "interview_date" TEXT,
  "interview_status" TEXT NOT NULL DEFAULT 'pending',
  "recognition_unlocked" INTEGER NOT NULL DEFAULT 0 CHECK ("recognition_unlocked" IN (0, 1)),
  "embassy_unlocked" INTEGER NOT NULL DEFAULT 0 CHECK ("embassy_unlocked" IN (0, 1)),
  "visa_granted" INTEGER NOT NULL DEFAULT 0 CHECK ("visa_granted" IN (0, 1)),
  "visa_date" TEXT,
  "flight_date" TEXT,
  "flight_info" TEXT,
  "docs_approved" INTEGER NOT NULL DEFAULT 0 CHECK ("docs_approved" IN (0, 1)),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "interview_type" TEXT,
  "interview_notes" TEXT,
  "integration_unlocked" INTEGER DEFAULT 0 CHECK ("integration_unlocked" IN (0, 1)),
  "start_unlocked" INTEGER DEFAULT 0 CHECK ("start_unlocked" IN (0, 1)),
  "interview1_status" TEXT,
  "interview2_status" TEXT,
  "visa_appt_date" TEXT,
  "housing_done" INTEGER CHECK ("housing_done" IN (0, 1)),
  "interview1_date" TEXT,
  "interview2_date" TEXT,
  "contract_done" INTEGER CHECK ("contract_done" IN (0, 1)),
  "recognition_done" INTEGER CHECK ("recognition_done" IN (0, 1)),
  "vorab_done" INTEGER CHECK ("vorab_done" IN (0, 1)),
  "docs_ready" INTEGER CHECK ("docs_ready" IN (0, 1)),
  "arrived_done" INTEGER CHECK ("arrived_done" IN (0, 1)),
  "interview1_held" INTEGER NOT NULL DEFAULT 0 CHECK ("interview1_held" IN (0, 1)),
  "interview2_held" INTEGER NOT NULL DEFAULT 0 CHECK ("interview2_held" IN (0, 1)),
  "interview1_date_confirmed" INTEGER NOT NULL DEFAULT 0 CHECK ("interview1_date_confirmed" IN (0, 1)),
  "interview2_date_confirmed" INTEGER NOT NULL DEFAULT 0 CHECK ("interview2_date_confirmed" IN (0, 1)),
  "interview1_result_date" TEXT,
  "interview2_result_date" TEXT,
  "interview1_result_date_confirmed" INTEGER NOT NULL DEFAULT 0 CHECK ("interview1_result_date_confirmed" IN (0, 1)),
  "interview2_result_date_confirmed" INTEGER NOT NULL DEFAULT 0 CHECK ("interview2_result_date_confirmed" IN (0, 1)),
  "visa_appt_date_confirmed" INTEGER NOT NULL DEFAULT 0 CHECK ("visa_appt_date_confirmed" IN (0, 1)),
  "flight_date_confirmed" INTEGER NOT NULL DEFAULT 0 CHECK ("flight_date_confirmed" IN (0, 1)),
  "interview_link_clicks" INTEGER NOT NULL DEFAULT 0,
  "interview_link_last_clicked_at" TEXT,
  "batch_id" TEXT,
  "funnel_stage" TEXT,
  "last_touch_at" TEXT,
  "employment_start" TEXT,
  "residence_permit_appt_date" TEXT,
  "agreement_signed" INTEGER CHECK ("agreement_signed" IN (0, 1)),
  "board_order" INTEGER,
  "pool_contacted" INTEGER NOT NULL DEFAULT 0 CHECK ("pool_contacted" IN (0, 1)),
  "pool_call_done" INTEGER NOT NULL DEFAULT 0 CHECK ("pool_call_done" IN (0, 1)),
  "pool_cv_done" INTEGER NOT NULL DEFAULT 0 CHECK ("pool_cv_done" IN (0, 1)),
  "pool_medical_done" INTEGER NOT NULL DEFAULT 0 CHECK ("pool_medical_done" IN (0, 1)),
  PRIMARY KEY ("user_id"),
  CONSTRAINT "candidate_pipeline_batch_id_fkey" FOREIGN KEY ("batch_id") REFERENCES "employer_batches" ("id") ON DELETE SET NULL ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "candidate_profiles" (
  "user_id" TEXT NOT NULL,
  "first_name" TEXT,
  "last_name" TEXT,
  "dob" TEXT,
  "nationality" TEXT,
  "passport_no" TEXT,
  "passport_expiry" TEXT,
  "raw_mrz" TEXT,
  "updated_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "place_of_birth" TEXT,
  "issuing_authority" TEXT,
  "address" TEXT,
  "city_of_residence" TEXT,
  "city_of_birth" TEXT,
  "country_of_birth" TEXT,
  "issue_date" TEXT,
  "address_street" TEXT,
  "address_number" TEXT,
  "address_postal" TEXT,
  "country_of_residence" TEXT,
  "passport_status" TEXT,
  "sex" TEXT,
  "passport_feedback" TEXT,
  "marital_status" TEXT,
  "children_ages" TEXT,
  "manually_verified" INTEGER NOT NULL DEFAULT 0 CHECK ("manually_verified" IN (0, 1)),
  "profile_photo" TEXT,
  "cv_draft" TEXT CHECK ("cv_draft" IS NULL OR json_valid("cv_draft")),
  "placement_ready" INTEGER NOT NULL DEFAULT 0 CHECK ("placement_ready" IN (0, 1)),
  "payment_tier" TEXT,
  "saved_signature" TEXT,
  "agency_id" TEXT,
  "passport_confirmed_fields" TEXT NOT NULL DEFAULT '[]' CHECK ("passport_confirmed_fields" IS NULL OR json_valid("passport_confirmed_fields")),
  "employer_id" TEXT,
  "phone" TEXT,
  "cv_use_agency_branding" INTEGER DEFAULT 1 CHECK ("cv_use_agency_branding" IN (0, 1)),
  "cv_use_borivon_branding" INTEGER DEFAULT 1 CHECK ("cv_use_borivon_branding" IN (0, 1)),
  "cover_letter_body" TEXT,
  "cover_letter_visa_body" TEXT,
  "b2_stage" TEXT NOT NULL DEFAULT 'not_started',
  "b2_failed" INTEGER NOT NULL DEFAULT 0 CHECK ("b2_failed" IN (0, 1)),
  "nursing_specialty" TEXT,
  "years_experience" INTEGER,
  "current_workplace" TEXT,
  "available_from" TEXT,
  "anerkennung_stage" TEXT,
  "last_msg_email_at" TEXT,
  "b2_exam_date" TEXT,
  "classroom_tester" INTEGER NOT NULL DEFAULT 0 CHECK ("classroom_tester" IN (0, 1)),
  "is_test_account" INTEGER NOT NULL DEFAULT 0 CHECK ("is_test_account" IN (0, 1)),
  "workplace_pref" TEXT,
  "lang" TEXT,
  "referred_by_affiliate" TEXT,
  PRIMARY KEY ("user_id"),
  CONSTRAINT "candidate_profiles_agency_id_fkey" FOREIGN KEY ("agency_id") REFERENCES "agencies" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "candidate_profiles_employer_id_fkey" FOREIGN KEY ("employer_id") REFERENCES "employers" ("id") ON DELETE SET NULL ON UPDATE NO ACTION,
  CONSTRAINT "candidate_profiles_passport_status_check" CHECK ((passport_status IN ('pending', 'approved', 'rejected'))),
  CONSTRAINT "candidate_profiles_lang_check" CHECK (((lang IS NULL) OR (lang IN ('fr', 'en', 'de'))))
);
CREATE TABLE IF NOT EXISTS "candidate_reminders" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "user_id" TEXT NOT NULL,
  "kind" TEXT NOT NULL DEFAULT 'documents',
  "items" TEXT NOT NULL DEFAULT '[]' CHECK ("items" IS NULL OR json_valid("items")),
  "sent_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS "candidate_self_reports" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "candidate_user_id" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "outcome" TEXT NOT NULL,
  "note" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS "candidate_status" (
  "user_id" TEXT NOT NULL,
  "b2_complete" INTEGER CHECK ("b2_complete" IN (0, 1)),
  "b2_cert_date" TEXT,
  "b2_next_exam_date" TEXT,
  "b2_next_exam_confirmed" INTEGER CHECK ("b2_next_exam_confirmed" IN (0, 1)),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "b2_exam_written" INTEGER CHECK ("b2_exam_written" IN (0, 1)),
  "b2_exam_written_date" TEXT,
  "b2_results_expected_date" TEXT,
  "b2_planned_exam_date" TEXT,
  "b2_registration_status" TEXT,
  "b2_notes" TEXT,
  "vaccines" TEXT CHECK ("vaccines" IS NULL OR json_valid("vaccines")),
  PRIMARY KEY ("user_id")
);
CREATE TABLE IF NOT EXISTS "classroom_consent" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "user_id" TEXT NOT NULL,
  "version" TEXT NOT NULL DEFAULT 'v1-2026-06',
  "consented_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "revoked_at" TEXT,
  "user_agent" TEXT,
  PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS "classroom_events" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "session_id" TEXT,
  "room_name" TEXT NOT NULL,
  "user_id" TEXT,
  "display_name" TEXT,
  "kind" TEXT NOT NULL,
  "value" TEXT NOT NULL DEFAULT '{}' CHECK ("value" IS NULL OR json_valid("value")),
  "source" TEXT NOT NULL DEFAULT 'client',
  "at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  CONSTRAINT "classroom_events_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "classroom_sessions" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "classroom_invites" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "session_id" TEXT NOT NULL,
  "user_id" TEXT NOT NULL,
  "invited_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id"),
  CONSTRAINT "classroom_invites_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "classroom_sessions" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "classroom_sessions" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "title" TEXT NOT NULL DEFAULT 'Live class',
  "room_name" TEXT NOT NULL,
  "host_user_id" TEXT,
  "status" TEXT NOT NULL DEFAULT 'live',
  "started_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "ended_at" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "open_to_candidates" INTEGER NOT NULL DEFAULT 0 CHECK ("open_to_candidates" IN (0, 1)),
  PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS "community_seen" (
  "user_id" TEXT NOT NULL,
  "seen_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("user_id")
);
CREATE TABLE IF NOT EXISTS "documents" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "user_id" TEXT NOT NULL,
  "file_name" TEXT NOT NULL,
  "file_path" TEXT NOT NULL,
  "file_type" TEXT DEFAULT 'Autre',
  "uploaded_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "status" TEXT DEFAULT 'pending',
  "feedback" TEXT,
  "drive_file_id" TEXT,
  "rotation" INTEGER NOT NULL DEFAULT 0,
  "uploaded_by_admin" INTEGER NOT NULL DEFAULT 0 CHECK ("uploaded_by_admin" IN (0, 1)),
  "signed_storage_path" TEXT,
  "r2_key" TEXT,
  "file_sha256" TEXT,
  "superseded_at" TEXT,
  "drive_mirror_id" TEXT,
  "drive_mirror_sha256" TEXT,
  "drive_mirror_batch_id" TEXT,
  PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS "email_followup_chase" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "owner_user_id" TEXT NOT NULL,
  "to_email" TEXT NOT NULL,
  "subject" TEXT NOT NULL DEFAULT '',
  "sent_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "last_nudge_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "nudge_count" INTEGER NOT NULL DEFAULT 0,
  "done" INTEGER NOT NULL DEFAULT 0 CHECK ("done" IN (0, 1)),
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00')
);
CREATE TABLE IF NOT EXISTS "employer_batches" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "employer_id" TEXT,
  "name" TEXT NOT NULL,
  "seats" INTEGER NOT NULL DEFAULT 10,
  "target_start" TEXT,
  "target_end" TEXT,
  "status" TEXT NOT NULL DEFAULT 'open',
  "notes" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "org_id" TEXT,
  PRIMARY KEY ("id"),
  CONSTRAINT "employer_batches_employer_id_fkey" FOREIGN KEY ("employer_id") REFERENCES "employers" ("id") ON DELETE SET NULL ON UPDATE NO ACTION,
  CONSTRAINT "employer_batches_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON DELETE SET NULL ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "employer_shortlists" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "org_id" TEXT,
  "employer_id" TEXT,
  "title" TEXT NOT NULL,
  "note" TEXT,
  "status" TEXT NOT NULL DEFAULT 'draft',
  "share_token" TEXT,
  "created_by" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id"),
  CONSTRAINT "employer_shortlists_employer_id_fkey" FOREIGN KEY ("employer_id") REFERENCES "employers" ("id") ON DELETE SET NULL ON UPDATE NO ACTION,
  CONSTRAINT "employer_shortlists_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "employers" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "slug" TEXT,
  "name" TEXT NOT NULL,
  "address_lines" TEXT NOT NULL CHECK ("address_lines" IS NULL OR json_valid("address_lines")),
  "agency_id" TEXT,
  "active" INTEGER NOT NULL DEFAULT 1 CHECK ("active" IN (0, 1)),
  "notes" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id"),
  CONSTRAINT "employers_agency_id_fkey" FOREIGN KEY ("agency_id") REFERENCES "organizations" ("id") ON DELETE SET NULL ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "enterprise_leads" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "name" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "company" TEXT NOT NULL DEFAULT '',
  "role" TEXT NOT NULL DEFAULT '',
  "phone" TEXT NOT NULL DEFAULT '',
  "headcount" TEXT NOT NULL DEFAULT '',
  "situations" TEXT NOT NULL DEFAULT '',
  "message" TEXT NOT NULL DEFAULT '',
  "lang" TEXT NOT NULL DEFAULT '',
  "source" TEXT NOT NULL DEFAULT 'v2-contact',
  "status" TEXT NOT NULL DEFAULT 'new',
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS "feed_comment_likes" (
  "comment_id" TEXT NOT NULL,
  "user_id" TEXT NOT NULL,
  PRIMARY KEY ("comment_id", "user_id"),
  CONSTRAINT "feed_comment_likes_comment_id_fkey" FOREIGN KEY ("comment_id") REFERENCES "feed_comments" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "feed_comments" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "post_id" TEXT NOT NULL,
  "user_id" TEXT NOT NULL,
  "content" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id"),
  CONSTRAINT "feed_comments_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "feed_posts" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT "feed_comments_content_check" CHECK (((length(content) >= 1) AND (length(content) <= 300)))
);
CREATE TABLE IF NOT EXISTS "feed_likes" (
  "post_id" TEXT NOT NULL,
  "user_id" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("post_id", "user_id"),
  CONSTRAINT "feed_likes_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "feed_posts" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "feed_posts" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "user_id" TEXT NOT NULL,
  "content" TEXT NOT NULL,
  "image_url" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "title" TEXT,
  "pinned" INTEGER NOT NULL DEFAULT 0 CHECK ("pinned" IN (0, 1)),
  "gif_url" TEXT,
  "category" TEXT NOT NULL DEFAULT 'general',
  "org_id" TEXT,
  PRIMARY KEY ("id"),
  CONSTRAINT "feed_posts_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT "feed_posts_content_check" CHECK (((length(content) >= 1) AND (length(content) <= 500))),
  CONSTRAINT "feed_posts_title_check" CHECK ((length(title) <= 100))
);
CREATE TABLE IF NOT EXISTS "gmail_signature_token" (
  "owner_user_id" TEXT NOT NULL,
  "refresh_token" TEXT,
  "access_token" TEXT,
  "expiry" TEXT,
  "google_email" TEXT,
  "signature_html" TEXT,
  "signature_fetched_at" TEXT,
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("owner_user_id")
);
CREATE TABLE IF NOT EXISTS "google_calendar_tokens" (
  "user_id" TEXT NOT NULL,
  "refresh_token" TEXT,
  "access_token" TEXT,
  "expiry" TEXT,
  "google_email" TEXT,
  "sees_all" INTEGER NOT NULL DEFAULT 0 CHECK ("sees_all" IN (0, 1)),
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("user_id")
);
CREATE TABLE IF NOT EXISTS "inbox_sla_nudges" (
  "key" TEXT NOT NULL,
  "nudged_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("key")
);
CREATE TABLE IF NOT EXISTS "interview_proposals" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "candidate_user_id" TEXT NOT NULL,
  "round" INTEGER NOT NULL DEFAULT 1,
  "proposed_slots" TEXT NOT NULL DEFAULT '[]' CHECK ("proposed_slots" IS NULL OR json_valid("proposed_slots")),
  "picked_slot" TEXT,
  "status" TEXT NOT NULL DEFAULT 'proposed',
  "note" TEXT,
  "created_by" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS "invite_tokens" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "org_id" TEXT,
  "type" TEXT NOT NULL,
  "code" TEXT NOT NULL,
  "used_by" TEXT,
  "used_at" TEXT,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "agency_id" TEXT,
  "invited_email" TEXT,
  PRIMARY KEY ("id"),
  CONSTRAINT "invite_tokens_agency_id_fkey" FOREIGN KEY ("agency_id") REFERENCES "agencies" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "invite_tokens_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT "invite_tokens_type_check" CHECK ((type IN ('candidate', 'member', 'sub-admin')))
);
CREATE TABLE IF NOT EXISTS "leads" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "kind" TEXT NOT NULL DEFAULT 'person',
  "email" TEXT NOT NULL,
  "name" TEXT NOT NULL DEFAULT '',
  "phone" TEXT NOT NULL DEFAULT '',
  "message" TEXT NOT NULL DEFAULT '',
  "details" TEXT NOT NULL DEFAULT '{}' CHECK ("details" IS NULL OR json_valid("details")),
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "status" TEXT NOT NULL DEFAULT 'new',
  "converted_at" TEXT,
  "candidate_user_id" TEXT,
  "ref_code" TEXT,
  PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS "messages" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "thread_user_id" TEXT NOT NULL,
  "sender_user_id" TEXT NOT NULL,
  "sender_role" TEXT NOT NULL,
  "body" TEXT NOT NULL DEFAULT '',
  "attachment" TEXT,
  "kind" TEXT NOT NULL DEFAULT 'message',
  "read_by_admin" INTEGER NOT NULL DEFAULT 0 CHECK ("read_by_admin" IN (0, 1)),
  "read_by_candidate" INTEGER NOT NULL DEFAULT 1 CHECK ("read_by_candidate" IN (0, 1)),
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "attachment_key" TEXT,
  "attachment_mime" TEXT,
  "has_attachment" INTEGER GENERATED ALWAYS AS (CASE WHEN "attachment_key" IS NOT NULL OR ("attachment" IS NOT NULL AND "attachment" <> '') THEN 1 ELSE 0 END) VIRTUAL,
  PRIMARY KEY ("id"),
  CONSTRAINT "messages_sender_role_check" CHECK ((sender_role IN ('candidate', 'admin'))),
  CONSTRAINT "messages_kind_check" CHECK ((kind IN ('message', 'bug')))
);
CREATE TABLE IF NOT EXISTS "notifications" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "user_id" TEXT NOT NULL,
  "doc_id" TEXT,
  "doc_name" TEXT NOT NULL,
  "doc_type" TEXT NOT NULL,
  "action" TEXT NOT NULL,
  "feedback" TEXT,
  "read" INTEGER NOT NULL DEFAULT 0 CHECK ("read" IN (0, 1)),
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id"),
  CONSTRAINT "notifications_action_check" CHECK ((action IN ('approved', 'rejected', 'verified', 'placed', 'sign_request', 'event_invite', 'follow_up', 'live_class')))
);
CREATE TABLE IF NOT EXISTS "online_course_registrations" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "first_name" TEXT NOT NULL DEFAULT '',
  "last_name" TEXT NOT NULL DEFAULT '',
  "email" TEXT NOT NULL,
  "phone" TEXT NOT NULL DEFAULT '',
  "address" TEXT NOT NULL DEFAULT '',
  "group_slot" TEXT NOT NULL DEFAULT '',
  "level" TEXT NOT NULL DEFAULT '',
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS "org_requirements" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "org_id" TEXT NOT NULL,
  "specialty" TEXT,
  "slots" INTEGER NOT NULL DEFAULT 1,
  "location" TEXT,
  "start_date" TEXT,
  "notes" TEXT,
  "active" INTEGER NOT NULL DEFAULT 1 CHECK ("active" IN (0, 1)),
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "bundesland" TEXT,
  "facility_type" TEXT,
  "city" TEXT,
  PRIMARY KEY ("id"),
  CONSTRAINT "org_requirements_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT "org_requirements_facility_type_check" CHECK ((facility_type IN ('Klinik', 'Altenheim', 'Ambulante Pflegedienst')))
);
CREATE TABLE IF NOT EXISTS "organization_members" (
  "org_id" TEXT NOT NULL,
  "sub_admin_email" TEXT NOT NULL,
  "role" TEXT NOT NULL DEFAULT 'member',
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("org_id", "sub_admin_email"),
  CONSTRAINT "organization_members_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT "organization_members_role_check" CHECK ((role IN ('member', 'owner')))
);
CREATE TABLE IF NOT EXISTS "organizations" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "name" TEXT NOT NULL,
  "invite_code" TEXT NOT NULL,
  "notes" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "logo_filename" TEXT,
  "footer_text" TEXT,
  "member_invite_code" TEXT,
  "agency_id" TEXT,
  "vaccine_req" TEXT NOT NULL DEFAULT '{}' CHECK ("vaccine_req" IS NULL OR json_valid("vaccine_req")),
  "required_doc_keys" TEXT CHECK ("required_doc_keys" IS NULL OR json_valid("required_doc_keys")),
  PRIMARY KEY ("id"),
  CONSTRAINT "organizations_agency_id_fkey" FOREIGN KEY ("agency_id") REFERENCES "agencies" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "partner_api_keys" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "org_id" TEXT NOT NULL,
  "key_hash" TEXT NOT NULL,
  "key_prefix" TEXT NOT NULL,
  "label" TEXT NOT NULL DEFAULT '',
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "created_by" TEXT,
  "last_used_at" TEXT,
  "revoked_at" TEXT,
  PRIMARY KEY ("id"),
  CONSTRAINT "partner_api_keys_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "partner_api_log" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "key_id" TEXT,
  "org_id" TEXT,
  "at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "path" TEXT NOT NULL,
  "candidate_user_id" TEXT,
  "document_id" TEXT,
  "status" INTEGER NOT NULL,
  CONSTRAINT "partner_api_log_key_id_fkey" FOREIGN KEY ("key_id") REFERENCES "partner_api_keys" ("id") ON DELETE SET NULL ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "partner_shares" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "org_id" TEXT NOT NULL,
  "candidate_user_id" TEXT NOT NULL,
  "shared_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "shared_by" TEXT,
  "revoked_at" TEXT,
  PRIMARY KEY ("id"),
  CONSTRAINT "partner_shares_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "pdf_field_mappings" (
  "signature" TEXT NOT NULL,
  "mappings" TEXT NOT NULL CHECK ("mappings" IS NULL OR json_valid("mappings")),
  "field_count" INTEGER NOT NULL DEFAULT 0,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "updated_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "created_by" TEXT,
  PRIMARY KEY ("signature")
);
CREATE TABLE IF NOT EXISTS "phase_doc_order" (
  "phase" TEXT NOT NULL,
  "order_keys" TEXT NOT NULL DEFAULT '[]' CHECK ("order_keys" IS NULL OR json_valid("order_keys")),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("phase")
);
CREATE TABLE IF NOT EXISTS "phase_slot_categories" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "org_id" TEXT,
  "phase" TEXT NOT NULL,
  "label" TEXT NOT NULL DEFAULT '',
  "position" INTEGER NOT NULL DEFAULT 0,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS "phase_slots" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "org_id" TEXT,
  "phase" TEXT NOT NULL,
  "position" INTEGER NOT NULL DEFAULT 0,
  "type" TEXT NOT NULL DEFAULT 'simple',
  "label" TEXT NOT NULL,
  "label_trans" TEXT,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "action_type" TEXT DEFAULT 'upload',
  "instructions" TEXT,
  "template_pdf_path" TEXT,
  "form_fields" TEXT CHECK ("form_fields" IS NULL OR json_valid("form_fields")),
  "admin_signs" INTEGER NOT NULL DEFAULT 0 CHECK ("admin_signs" IN (0, 1)),
  "candidate_signs" INTEGER NOT NULL DEFAULT 0 CHECK ("candidate_signs" IN (0, 1)),
  "admin_fills" INTEGER NOT NULL DEFAULT 0 CHECK ("admin_fills" IN (0, 1)),
  "candidate_fills" INTEGER NOT NULL DEFAULT 0 CHECK ("candidate_fills" IN (0, 1)),
  "candidate_signature_zone" TEXT CHECK ("candidate_signature_zone" IS NULL OR json_valid("candidate_signature_zone")),
  "pdf_has_native_fields" INTEGER NOT NULL DEFAULT 0 CHECK ("pdf_has_native_fields" IN (0, 1)),
  "category_id" TEXT,
  "employer_id" TEXT,
  "is_required" INTEGER NOT NULL DEFAULT 1 CHECK ("is_required" IN (0, 1)),
  PRIMARY KEY ("id"),
  CONSTRAINT "phase_slots_category_fk" FOREIGN KEY ("category_id") REFERENCES "phase_slot_categories" ("id") ON DELETE SET NULL ON UPDATE NO ACTION,
  CONSTRAINT "phase_slots_employer_id_fkey" FOREIGN KEY ("employer_id") REFERENCES "employers" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT "phase_slots_phase_check" CHECK ((phase IN ('bearbeitung', 'visum'))),
  CONSTRAINT "phase_slots_type_check" CHECK ((type IN ('simple', 'dual')))
);
CREATE TABLE IF NOT EXISTS "rate_limits" (
  "bucket_key" TEXT NOT NULL,
  "window_start" INTEGER NOT NULL,
  "count" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("bucket_key", "window_start")
);
CREATE TABLE IF NOT EXISTS "shortlist_candidates" (
  "shortlist_id" TEXT NOT NULL,
  "candidate_user_id" TEXT NOT NULL,
  "position" INTEGER NOT NULL DEFAULT 0,
  "admin_note" TEXT,
  "added_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("shortlist_id", "candidate_user_id"),
  CONSTRAINT "shortlist_candidates_shortlist_id_fkey" FOREIGN KEY ("shortlist_id") REFERENCES "employer_shortlists" ("id") ON DELETE CASCADE ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "sign_requests" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "candidate_user_id" TEXT NOT NULL,
  "created_by_email" TEXT NOT NULL,
  "document_name" TEXT NOT NULL,
  "note" TEXT,
  "pdf_storage_path" TEXT,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "signed_at" TEXT,
  "signed_pdf_path" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "signature_zone" TEXT,
  "viewed_at" TEXT,
  "review_status" TEXT,
  "review_feedback" TEXT,
  PRIMARY KEY ("id"),
  CONSTRAINT "sign_requests_review_status_check" CHECK ((review_status IN ('accepted', 'rejected')))
);
CREATE TABLE IF NOT EXISTS "sub_admin_assignments" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "sub_admin_email" TEXT NOT NULL,
  "candidate_user_id" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS "sub_admins" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "email" TEXT NOT NULL,
  "name" TEXT NOT NULL DEFAULT '',
  "label" TEXT NOT NULL DEFAULT '',
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "agency_id" TEXT,
  "is_agency_admin" INTEGER NOT NULL DEFAULT 0 CHECK ("is_agency_admin" IN (0, 1)),
  PRIMARY KEY ("id"),
  CONSTRAINT "sub_admins_agency_id_fkey" FOREIGN KEY ("agency_id") REFERENCES "agencies" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "suggested_matches" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "candidate_user_id" TEXT NOT NULL,
  "org_id" TEXT NOT NULL,
  "requirement_id" TEXT,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "suggested_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "decided_at" TEXT,
  "decided_by" TEXT,
  PRIMARY KEY ("id"),
  CONSTRAINT "suggested_matches_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations" ("id") ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT "suggested_matches_requirement_id_fkey" FOREIGN KEY ("requirement_id") REFERENCES "org_requirements" ("id") ON DELETE SET NULL ON UPDATE NO ACTION
);
CREATE TABLE IF NOT EXISTS "telegram_updates" (
  "update_id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  "responded_at" TEXT
);
CREATE TABLE IF NOT EXISTS "upload_links" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab', 1 + (abs(random()) % 4), 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))),
  "token_hash" TEXT NOT NULL,
  "candidate_user_id" TEXT NOT NULL,
  "doc_keys" TEXT NOT NULL CHECK ("doc_keys" IS NULL OR json_valid("doc_keys")),
  "uploaded_keys" TEXT NOT NULL DEFAULT '[]' CHECK ("uploaded_keys" IS NULL OR json_valid("uploaded_keys")),
  "created_by" TEXT,
  "expires_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now','+7 days') || '000+00:00'),
  "used_at" TEXT,
  "revoked_at" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00'),
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_journey_due" ON "candidate_journey_items" (candidate_user_id, done, due_date);
CREATE INDEX IF NOT EXISTS "idx_journey_candidate" ON "candidate_journey_items" (candidate_user_id);
CREATE UNIQUE INDEX IF NOT EXISTS "uq_journey_preset" ON "candidate_journey_items" (candidate_user_id, preset_key);
CREATE INDEX IF NOT EXISTS "assistant_reminders_owner_idx" ON "assistant_reminders" (owner_user_id, done, due_date);
CREATE INDEX IF NOT EXISTS "assistant_reminders_ping_idx" ON "assistant_reminders" (owner_user_id, last_ping_message_id) WHERE (last_ping_message_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS "assistant_reminders_due_at_idx" ON "assistant_reminders" (done, notified_at, due_at);
CREATE INDEX IF NOT EXISTS "assistant_memory_owner_idx" ON "assistant_memory" (owner_user_id, created_at);
CREATE INDEX IF NOT EXISTS "feed_clikes_comment_id_idx" ON "feed_comment_likes" (comment_id);
CREATE INDEX IF NOT EXISTS "idx_self_reports_candidate" ON "candidate_self_reports" (candidate_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS "assistant_pending_actions_owner_idx" ON "assistant_pending_actions" (owner_user_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS "idx_inbox_sla_nudges_at" ON "inbox_sla_nudges" (nudged_at);
CREATE UNIQUE INDEX IF NOT EXISTS "employer_shortlists_share_token_key" ON "employer_shortlists" (share_token);
CREATE INDEX IF NOT EXISTS "idx_employer_shortlists_org" ON "employer_shortlists" (org_id);
CREATE INDEX IF NOT EXISTS "idx_employer_shortlists_token" ON "employer_shortlists" (share_token);
CREATE INDEX IF NOT EXISTS "idx_shortlist_candidates_sl" ON "shortlist_candidates" (shortlist_id);
CREATE INDEX IF NOT EXISTS "messages_thread_idx" ON "messages" (thread_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS "messages_unread_admin_idx" ON "messages" (read_by_admin) WHERE (read_by_admin = 0);
CREATE INDEX IF NOT EXISTS "messages_created_at_idx" ON "messages" (created_at DESC);
CREATE INDEX IF NOT EXISTS "messages_thread_user_id_idx" ON "messages" (thread_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS "messages_sender_user_id_idx" ON "messages" (sender_user_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS "suggested_matches_candidate_user_id_org_id_key" ON "suggested_matches" (candidate_user_id, org_id);
CREATE INDEX IF NOT EXISTS "notifications_user_id_idx" ON "notifications" (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS "notifications_user_unread_idx" ON "notifications" (user_id) WHERE (read = 0);
CREATE INDEX IF NOT EXISTS "feed_likes_post_id_idx" ON "feed_likes" (post_id);
CREATE INDEX IF NOT EXISTS "feed_posts_created_at_idx" ON "feed_posts" (pinned DESC, created_at DESC);
CREATE INDEX IF NOT EXISTS "feed_posts_org_id_idx" ON "feed_posts" (org_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS "sub_admin_assignments_sub_admin_email_candidate_user_id_key" ON "sub_admin_assignments" (sub_admin_email, candidate_user_id);
CREATE INDEX IF NOT EXISTS "sub_admin_assignments_email_idx" ON "sub_admin_assignments" (sub_admin_email);
CREATE INDEX IF NOT EXISTS "sub_admin_assignments_candidate_idx" ON "sub_admin_assignments" (candidate_user_id);
CREATE INDEX IF NOT EXISTS "sign_requests_candidate_user_id_idx" ON "sign_requests" (candidate_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS "sign_requests_status_idx" ON "sign_requests" (status) WHERE (status = 'pending');
CREATE INDEX IF NOT EXISTS "idx_interview_proposals_cand" ON "interview_proposals" (candidate_user_id, status);
CREATE INDEX IF NOT EXISTS "feed_comments_created_at_idx" ON "feed_comments" (created_at DESC);
CREATE INDEX IF NOT EXISTS "feed_comments_post_id_idx" ON "feed_comments" (post_id, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS "sub_admins_email_key" ON "sub_admins" (email);
CREATE INDEX IF NOT EXISTS "idx_assistant_token_usage_created" ON "assistant_token_usage" (created_at);
CREATE UNIQUE INDEX IF NOT EXISTS "organizations_invite_code_key" ON "organizations" (invite_code);
CREATE INDEX IF NOT EXISTS "idx_organizations_invite_code" ON "organizations" (invite_code);
CREATE UNIQUE INDEX IF NOT EXISTS "organizations_member_invite_code_key" ON "organizations" (member_invite_code);
CREATE INDEX IF NOT EXISTS "candidate_notes_candidate_idx" ON "candidate_notes" (candidate_user_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS "invite_tokens_code_key" ON "invite_tokens" (code);
CREATE INDEX IF NOT EXISTS "invite_tokens_code_idx" ON "invite_tokens" (code);
CREATE INDEX IF NOT EXISTS "invite_tokens_org_id_idx" ON "invite_tokens" (org_id) WHERE (org_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS "idx_organization_members_email" ON "organization_members" (sub_admin_email);
CREATE INDEX IF NOT EXISTS "idx_candidate_organizations_org" ON "candidate_organizations" (org_id);
CREATE INDEX IF NOT EXISTS "idx_candidate_organizations_user" ON "candidate_organizations" (candidate_user_id);
CREATE INDEX IF NOT EXISTS "idx_candidate_organizations_status" ON "candidate_organizations" (status);
CREATE INDEX IF NOT EXISTS "bookings_upcoming_idx" ON "bookings" (starts_at DESC);
CREATE INDEX IF NOT EXISTS "bookings_status_idx" ON "bookings" (status, starts_at);
CREATE UNIQUE INDEX IF NOT EXISTS "bookings_manage_token_key" ON "bookings" (manage_token) WHERE (manage_token IS NOT NULL);
CREATE INDEX IF NOT EXISTS "bookings_reminder_due_idx" ON "bookings" (starts_at) WHERE ((reminded_at IS NULL) AND (status = 'booked'));
CREATE UNIQUE INDEX IF NOT EXISTS "bookings_slot_host_unique" ON "bookings" (starts_at, COALESCE(host_id, (0))) WHERE (status <> 'cancelled');
CREATE INDEX IF NOT EXISTS "candidate_profiles_employer_idx" ON "candidate_profiles" (employer_id);
CREATE INDEX IF NOT EXISTS "candidate_profiles_passport_status_idx" ON "candidate_profiles" (passport_status) WHERE (passport_status = 'pending');
CREATE INDEX IF NOT EXISTS "candidate_profiles_agency_id_idx" ON "candidate_profiles" (agency_id) WHERE (agency_id IS NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "affiliates_code_key" ON "affiliates" (code);
CREATE UNIQUE INDEX IF NOT EXISTS "affiliates_dash_token_hash_key" ON "affiliates" (dash_token_hash);
CREATE INDEX IF NOT EXISTS "affiliates_code_idx" ON "affiliates" (code);
CREATE INDEX IF NOT EXISTS "affiliates_dash_idx" ON "affiliates" (dash_token_hash);
CREATE UNIQUE INDEX IF NOT EXISTS "affiliate_earnings_affiliate_id_candidate_user_id_key" ON "affiliate_earnings" (affiliate_id, candidate_user_id);
CREATE INDEX IF NOT EXISTS "affiliate_earnings_aff_idx" ON "affiliate_earnings" (affiliate_id);
CREATE INDEX IF NOT EXISTS "idx_academy_cohorts_scope" ON "academy_cohorts" (org_id, status);
CREATE INDEX IF NOT EXISTS "idx_academy_members_candidate" ON "academy_cohort_members" (candidate_user_id);
CREATE INDEX IF NOT EXISTS "idx_academy_lessons_level" ON "academy_lessons" (level, "position");
CREATE INDEX IF NOT EXISTS "idx_academy_sessions_cohort" ON "academy_class_sessions" (cohort_id, starts_at);
CREATE UNIQUE INDEX IF NOT EXISTS "academy_attendance_session_id_candidate_user_id_key" ON "academy_attendance" (session_id, candidate_user_id);
CREATE INDEX IF NOT EXISTS "idx_academy_attendance_candidate" ON "academy_attendance" (candidate_user_id);
CREATE INDEX IF NOT EXISTS "idx_academy_quizzes_scope" ON "academy_quizzes" (cohort_id, level, due_at);
CREATE UNIQUE INDEX IF NOT EXISTS "academy_submissions_quiz_id_candidate_user_id_key" ON "academy_submissions" (quiz_id, candidate_user_id);
CREATE INDEX IF NOT EXISTS "idx_academy_submissions_candidate" ON "academy_submissions" (candidate_user_id);
CREATE UNIQUE INDEX IF NOT EXISTS "uq_academy_point_event" ON "academy_point_events" (candidate_user_id, type, source_kind, source_id);
CREATE INDEX IF NOT EXISTS "idx_academy_points_candidate" ON "academy_point_events" (candidate_user_id, created_at);
CREATE INDEX IF NOT EXISTS "idx_academy_points_cohort_week" ON "academy_point_events" (cohort_id, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS "academy_badges_key_key" ON "academy_badges" (key);
CREATE UNIQUE INDEX IF NOT EXISTS "academy_student_badges_candidate_user_id_badge_id_key" ON "academy_student_badges" (candidate_user_id, badge_id);
CREATE INDEX IF NOT EXISTS "idx_academy_student_badges_candidate" ON "academy_student_badges" (candidate_user_id);
CREATE INDEX IF NOT EXISTS "candidate_pipeline_board_order_idx" ON "candidate_pipeline" (batch_id, board_order);
CREATE INDEX IF NOT EXISTS "candidate_pipeline_pool_idx" ON "candidate_pipeline" (batch_id) WHERE (batch_id IS NULL);
CREATE INDEX IF NOT EXISTS "idx_candidate_pipeline_batch" ON "candidate_pipeline" (batch_id);
CREATE INDEX IF NOT EXISTS "idx_candidate_pipeline_funnel" ON "candidate_pipeline" (funnel_stage);
CREATE INDEX IF NOT EXISTS "rate_limits_window_idx" ON "rate_limits" (window_start);
CREATE INDEX IF NOT EXISTS "documents_uploaded_at_idx" ON "documents" (uploaded_at DESC);
CREATE INDEX IF NOT EXISTS "documents_active_idx" ON "documents" (user_id) WHERE (superseded_at IS NULL);
CREATE INDEX IF NOT EXISTS "documents_drive_mirror_idx" ON "documents" (user_id) WHERE ((status = 'approved') AND (r2_key IS NOT NULL));
CREATE INDEX IF NOT EXISTS "documents_user_id_idx" ON "documents" (user_id);
CREATE INDEX IF NOT EXISTS "documents_user_id_file_type_idx" ON "documents" (user_id, file_type);
CREATE INDEX IF NOT EXISTS "documents_drive_file_id_idx" ON "documents" (drive_file_id) WHERE (drive_file_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS "documents_r2_key_idx" ON "documents" (r2_key) WHERE (r2_key IS NOT NULL);
CREATE INDEX IF NOT EXISTS "documents_sha256_idx" ON "documents" (file_sha256) WHERE (file_sha256 IS NOT NULL);
CREATE INDEX IF NOT EXISTS "idx_enterprise_leads_created_at" ON "enterprise_leads" (created_at DESC);
CREATE INDEX IF NOT EXISTS "idx_enterprise_leads_email" ON "enterprise_leads" (email);
CREATE INDEX IF NOT EXISTS "candidate_reminders_user_idx" ON "candidate_reminders" (user_id, sent_at DESC);
CREATE INDEX IF NOT EXISTS "idx_ocr_created_at" ON "online_course_registrations" (created_at DESC);
CREATE INDEX IF NOT EXISTS "idx_ocr_email" ON "online_course_registrations" (email);
CREATE INDEX IF NOT EXISTS "idx_email_followup_chase_open" ON "email_followup_chase" (owner_user_id, done, last_nudge_at);
CREATE INDEX IF NOT EXISTS "idx_classroom_events_session" ON "classroom_events" (session_id);
CREATE INDEX IF NOT EXISTS "idx_classroom_events_user" ON "classroom_events" (user_id);
CREATE INDEX IF NOT EXISTS "idx_classroom_events_kind" ON "classroom_events" (kind);
CREATE UNIQUE INDEX IF NOT EXISTS "classroom_sessions_room_name_key" ON "classroom_sessions" (room_name);
CREATE INDEX IF NOT EXISTS "idx_classroom_sessions_room" ON "classroom_sessions" (room_name);
CREATE INDEX IF NOT EXISTS "idx_classroom_sessions_open_live" ON "classroom_sessions" (status, open_to_candidates);
CREATE INDEX IF NOT EXISTS "admin_notifications_user_email_idx" ON "admin_notifications" (user_email);
CREATE INDEX IF NOT EXISTS "admin_notifications_unread_idx" ON "admin_notifications" (read, created_at DESC) WHERE (read = 0);
CREATE INDEX IF NOT EXISTS "admin_notifications_created_at_idx" ON "admin_notifications" (created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS "classroom_consent_user_id_key" ON "classroom_consent" (user_id);
CREATE INDEX IF NOT EXISTS "idx_classroom_consent_user" ON "classroom_consent" (user_id);
CREATE INDEX IF NOT EXISTS "idx_leads_created_at" ON "leads" (created_at DESC);
CREATE INDEX IF NOT EXISTS "idx_leads_email" ON "leads" (email);
CREATE INDEX IF NOT EXISTS "leads_status_idx" ON "leads" (status, created_at DESC);
CREATE INDEX IF NOT EXISTS "assistant_chat_turns_owner_created_idx" ON "assistant_chat_turns" (owner_user_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS "assistant_commitments_src_idx" ON "assistant_commitments" (owner_user_id, COALESCE(source_message_id, ''), what);
CREATE INDEX IF NOT EXISTS "assistant_commitments_open_idx" ON "assistant_commitments" (owner_user_id, status, due_at);
CREATE UNIQUE INDEX IF NOT EXISTS "assistant_commitments_owner_src_what" ON "assistant_commitments" (owner_user_id, source_message_id, what);
CREATE INDEX IF NOT EXISTS "idx_employer_batches_status" ON "employer_batches" (status);
CREATE INDEX IF NOT EXISTS "employer_batches_org_idx" ON "employer_batches" (org_id);
CREATE INDEX IF NOT EXISTS "idx_calendar_events_starts" ON "calendar_events" (starts_at DESC);
CREATE INDEX IF NOT EXISTS "phase_slots_org_phase_pos" ON "phase_slots" (org_id, phase, "position");
CREATE INDEX IF NOT EXISTS "phase_slots_org_phase_idx" ON "phase_slots" (org_id, phase, "position");
CREATE INDEX IF NOT EXISTS "phase_slots_category_idx" ON "phase_slots" (category_id) WHERE (category_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS "phase_slots_employer_phase_pos" ON "phase_slots" (employer_id, phase, "position");
CREATE INDEX IF NOT EXISTS "pdf_field_mappings_updated_idx" ON "pdf_field_mappings" (updated_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS "classroom_invites_session_id_user_id_key" ON "classroom_invites" (session_id, user_id);
CREATE INDEX IF NOT EXISTS "idx_classroom_invites_user" ON "classroom_invites" (user_id);
CREATE INDEX IF NOT EXISTS "idx_classroom_invites_session" ON "classroom_invites" (session_id);
CREATE INDEX IF NOT EXISTS "idx_assistant_sent_emails_owner" ON "assistant_sent_emails" (owner_user_id, sent_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS "booking_hosts_email_uniq" ON "booking_hosts" (lower(email));
CREATE UNIQUE INDEX IF NOT EXISTS "employers_slug_key" ON "employers" (slug);
CREATE INDEX IF NOT EXISTS "employers_active_idx" ON "employers" (active);
CREATE INDEX IF NOT EXISTS "employers_agency_idx" ON "employers" (agency_id);
CREATE INDEX IF NOT EXISTS "idx_admin_checklist_personal" ON "admin_checklist_items" (owner_email) WHERE (scope = 'personal');
CREATE INDEX IF NOT EXISTS "idx_admin_checklist_shared" ON "admin_checklist_items" (org_id) WHERE (scope = 'shared');
CREATE INDEX IF NOT EXISTS "idx_admin_checklist_shared_hq" ON "admin_checklist_items" (org_id) WHERE (scope = 'shared_hq');
CREATE INDEX IF NOT EXISTS "phase_slot_categories_scope_idx" ON "phase_slot_categories" (phase, org_id, "position");
CREATE UNIQUE INDEX IF NOT EXISTS "partner_api_keys_key_hash_key" ON "partner_api_keys" (key_hash);
CREATE INDEX IF NOT EXISTS "partner_api_keys_hash_idx" ON "partner_api_keys" (key_hash) WHERE (revoked_at IS NULL);
CREATE INDEX IF NOT EXISTS "partner_api_keys_org_idx" ON "partner_api_keys" (org_id);
CREATE UNIQUE INDEX IF NOT EXISTS "partner_shares_unique" ON "partner_shares" (org_id, candidate_user_id);
CREATE INDEX IF NOT EXISTS "partner_shares_live_idx" ON "partner_shares" (org_id) WHERE (revoked_at IS NULL);
CREATE INDEX IF NOT EXISTS "partner_api_log_at_idx" ON "partner_api_log" (at DESC);
CREATE INDEX IF NOT EXISTS "partner_api_log_org_idx" ON "partner_api_log" (org_id, at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS "upload_links_token_hash_key" ON "upload_links" (token_hash);
CREATE INDEX IF NOT EXISTS "idx_upload_links_hash" ON "upload_links" (token_hash);
CREATE INDEX IF NOT EXISTS "idx_upload_links_candidate" ON "upload_links" (candidate_user_id);

CREATE TRIGGER IF NOT EXISTS "employers_set_updated_at" AFTER UPDATE ON "employers" FOR EACH ROW WHEN NEW."updated_at" IS OLD."updated_at"
BEGIN UPDATE "employers" SET "updated_at" = (strftime('%Y-%m-%dT%H:%M:%f','now') || '000+00:00') WHERE "id" = NEW."id"; END;
